### ISSUE TITLE
I can hit before game starts... 

### ISSUE THREAD

**Issue by LordJoshie** [ImagicalGamer/SurvivalGamesV3#102]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

XX = required

This issue thing is confusing.... good job. 

Anyways, I can hit before game starts... I havent tested much, but I know thats one issue. & I believe this game doesn't 'end' when there is one person left standing. 
There should be a period of time where players can gather resources before pvp begins.

Also, in your main page description, you misspelled Genisys.   .... Genysis ?

**Comment by Heroata** [comment]
I pulled code for fix game end. Wait for it.

**Comment by Heroata** [comment]
And if nobody do, i'll do this 10 second (or configurable) invincible time at start.

**Comment by LordJoshie** [comment]
beautiful. thanks for the fast reply.

this is a wonderful plugin.

unfortunately I was banned off ImagicalMine forums for posting an issue
similar... about AntiCheat not working on Genisys... :/

I know nothing about making a plug tho... just editing strings &
configurations.

this plugin is definitely nice tho.

**Comment by EpicSteve33** [comment]
I know why it lets you hit players

**Comment by LordJoshie** [comment]
okay.... why ? & why wouldn't you have said so in the post you just made ?

**Comment by EpicSteve33** [comment]
The code it only set to 15 seconds after the games starts the count down so to fix this set it to 75 because that gives it 15seconds + the 60seconds waiting time

**Comment by EpicSteve33** [comment]
Lol

**Comment by LordJoshie** [comment]
ohh. okay. killer.
how about being warped to hub when game done ? & a reward ?

**Comment by EpicSteve33** [comment]
a reward thing was added in a older version but was removed and idk about the warp yet

**Comment by EpicSteve33** [comment]
#104 this should fix this issue

**Comment by Dev-Kevo** [comment]
I think i got the code

**Comment by Dev-Kevo** [comment]
But i am not home :/

**Comment by ImagicalGamer** [comment]
@LordJoshie you are teleported when the game ends and a reward will be re added soon, were focusing on the Grace Period rn.

**Comment by LordJoshie** [comment]
okay thanks. & I dunno... for me... the game didn't end when I was the last
person left standing. :/

**Comment by EpicSteve33** [comment]
@LordJoshie it's a bug that we all are working on

**Comment by EpicSteve33** [comment]
@ImagicalGamer can I have collaboration permission?

**Comment by LordJoshie** [comment]
okay, no worries. it's a great plugin in progress. gonna be used by many
I'm sure. I'm looking forward to my server having this for some gaming. :D
great work. I'll be checking in & testing future releases.

**Comment by EpicSteve33** [comment]
This plugin has got some good developers behind it so we will get it done someday lel

**Comment by LordJoshie** [comment]
I'm sure someday very soon.
if anyone here wants to add my Kik for private chat  Dark.Miner

I own play.purecraftpe.ca & I'm working on networking my servers to have a
couple setup for gaming & reduce the load on my main server  I'm ranked #28
in under two months being public.

So having the best plugs is important to me. :)
On Apr 21, 2016 1:40 PM, "EpicSteve33" <notifications@github.com> wrote:

This plugin has got some good developers behind it so we will get it done
someday lel

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/ImagicalGamer/SurvivalGamesV3/issues/102#issuecomment-213032465>
