### ISSUE TITLE
Non-OP Players Can't Open Chest

### ISSUE THREAD

**Issue by Heroata** [ImagicalGamer/SurvivalGamesV3#103]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

XX = required

Non op players can not open chest. (Don't sure is it cause from my other plugins)

**Comment by remotevase** [comment]
This is unsupported by your version of PM (ImagicalMine doesnt support, PocketMine doesnt support, Genysis doesnt, clearsky doesnt, nukkit doesnt, bukkitpe doesnt, gladiatormine doesnt etc) No one has figured out this...

**Comment by Heroata** [comment]
What??? Didnt understand :/ which version should i use?

**Comment by Dev-Kevo** [comment]
Its works for me :/

**Comment by remotevase** [comment]
@Heroata none fully support it

**Comment by Heroata** [comment]
Oh this time another plugin causes
