### ISSUE TITLE
Fix All Bugs for Genisys!

### ISSUE THREAD

**Issue by CLiu13** [ImagicalGamer/SurvivalGamesV3#11]
For example, when players die, the game still registers them as an active player.

**Comment by ImagicalGamer** [comment]
I can't seem to re-create this, if your default world is the same as the SG arena this will happen.

**Comment by Driesboy** [comment]
no its not he same world 
0/24 players in arena
sign say running 
and no players can kom naar deze clan

**Comment by ImagicalGamer** [comment]
That's not a bug. That happens when the arena is corrupted or the world is corrupted.

**Comment by CLiu13** [comment]
Alright, I will test this out with two different worlds.

**Comment by Driesboy** [comment]
its bug
i have name the world/ Map2
and lobby world Lobby

**Comment by ImagicalGamer** [comment]
I know the current bugs with my plugin and that's not one of them. That's a Genisys bug, the only system that error has occurred on is Genisys.
