### ISSUE TITLE
Having Trouble Using SurvivalGamesV3

### ISSUE THREAD

**Issue by Pandaken** [ImagicalGamer/SurvivalGamesV3#118]
Hello! I am unsure how to use this plugin (this is unlike many other plugins I have seen). Do I have to upload the config, plugin, rank, .yml and README.md and the survival games v3 php file and unstable file? Isn't the plugin supposed to be a .phar (like my others)? Have I downloaded the right thing? If possible, I'd like the proper step process given to me on how to use this plugin for my server. Thank you for your help in advance, it is greatly appreciated.

**Comment by ImagicalGamer** [comment]
Yes [THIS](https://github.com/ImagicalGamer/SurvivalGamesV3/releases/download/V3.0.7/SurvivalGamesStable.phar)

**Comment by Pandaken** [comment]
Thank you very much it works! However, is there anyway you can give me this plugin without the kit part?   (Because some players in my server randomly got the athlete kit and effects) Thank you again in advance!

**Comment by remotevase** [comment]
Sure, I'll make 2 new branches tmro
1) no kits
2) no ranks

**Comment by Pandaken** [comment]
Okay thank you!

**Comment by Driesboy** [comment]
i have added the best support for that

**Comment by Taki21** [comment]
We dont need branches @remotevase we can use config for decisions xD and @Driesboy did dat already :P
