### ISSUE TITLE
Moving issues [GENISYS]

### ISSUE THREAD

**Issue by TheGalaxyLord** [ImagicalGamer/SurvivalGamesV3#12]
Apparently when people are still before the match u can kinda glitch and be able to move out of the spawn pad thing and open the chests

**Comment by ImagicalGamer** [comment]
Sorry about that, issue will be fixed in version V3.0.2. What IM version are you running?

**Comment by TheGalaxyLord** [comment]
I am using Genisys

**Comment by ImagicalGamer** [comment]
That's why it's not working, it was made for PocketMine and ImagicalMine only, too many PHP7 errors when running Genisys.

**Comment by ImagicalGamer** [comment]
I will make a Genisys edition.

**Comment by ImagicalGamer** [comment]
Issue closed, Reason: Known Issue, will be resolved with Genisys edition.
