### ISSUE TITLE
Downloading New Support Phar. For SurvivalGamesV3

### ISSUE THREAD

**Issue by Pandaken** [ImagicalGamer/SurvivalGamesV3#124]
Hello! Sorry If I'm asking too many questions, but how do you download the phar of the entire plugin including the support for disabling kits and ranks? I only see zip. download. Thank you in advance.

**Comment by remotevase** [comment]
I will make a release for that now and post it to ImagicalMine forums

**Comment by Pandaken** [comment]
Can you give me the download here because ImagicalMine Forums hasn't confirmed my account yet and this is the only place I can download as of right now

**Comment by remotevase** [comment]
https://forums.imagicalmine.net/plugins/survival-games.284/download?version=475
