### ISSUE TITLE
Downloading SurvivalGames V3 support for kit removal phar. file 

### ISSUE THREAD

**Issue by Pandaken** [ImagicalGamer/SurvivalGamesV3#126]
Sorry for my issues but Imagicalmine still hasn't confirmed my account and I can't download the new update. Can I have the download here instead?

**Comment by Taki21** [comment]
Why do u wanna remove kits?

**Comment by Taki21** [comment]
It makes our lives hardr

**Comment by remotevase** [comment]
https://forums.imagicalmine.net/plugins/survival-games.284/download?version=475

Option to disable kits already there. Stop spamming the issues with these threads or we'll ban you from this repo
