### ISSUE TITLE
(Not Spam) Reread previous, issue, Not Resolved.

### ISSUE THREAD

**Issue by Pandaken** [ImagicalGamer/SurvivalGamesV3#127]
The previous issue wasn't resolved! I said Imagicalmine didn't confirm my account so I can't download anything from imagicalmine. What i am asking for is a link download (Like ImagicalGamer gave me) so I can download it here. Thank you, and sorry.

**Comment by remotevase** [comment]
https://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/3.1.1
