### ISSUE TITLE
Server crash?

### ISSUE THREAD

**Issue by Pandaken** [ImagicalGamer/SurvivalGamesV3#129]
Hello. I was wondering if there was a solution to my server crashing every time i put the latest release of survival games v3 .phar in. Once I upload the .phar and restart the server the console says:

28.04 11:05:08 [Multicraft] Server stopped
28.04 11:05:08 [Multicraft] Restarting crashed server in 15 seconds
28.04 11:05:08 [Multicraft] Server shut down (starting)
28.04 11:05:06 [Server] INFO [11:05:06] emergency> Please upload the "/CrashDump_Thu_Apr_28-11.05.06-EDT_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
28.04 11:05:06 [Server] INFO [11:05:06] emergency> An unrecoverable error has occurred and the server has crashed. Creating a crash dump
28.04 11:05:06 [Server] INFO [11:05:06] critical> ParseError: "syntax error, unexpected '-', expecting ',' or ';'" (EXCEPTION) in "/S-W.Ultimate.phar/src/SWUltimate/Loader" at line 27
28.04 11:05:06 [Server] INFO [11:05:06] system> Loading S-W-Ultimate v1

Any solutions? Thanks in advance.

**Comment by ImagicalGamer** [comment]
That's SW ultimate not the same as SGV3

**Comment by Pandaken** [comment]
Do I have to upload both the SW and SGV3 for the no kits option to work?

**Comment by Taki21** [comment]
in the sgv3 config there is an option to enable disable kits

**Comment by remotevase** [comment]
SW Ultimate is my plugin
http://github.com/remote_vase/S-W-Ultimate
Completely different from this plugin, plus, my plugin is not even completed yet
