### ISSUE TITLE
Match doesn't start [GENISYS]

### ISSUE THREAD

**Issue by TheGalaxyLord** [ImagicalGamer/SurvivalGamesV3#13]
For some reasons the match doesn't wanna start it keeps getting stuck at 0 seconds and then nothing happens.

**Comment by ImagicalGamer** [comment]
Reset your Config, some of these are ImagicalMine bugs that I have no control over, I'm trying to re-create this issue now.

**Comment by ImagicalGamer** [comment]
Genisys issue, numerous Genisys bugs caused by PHP7 fixing now.
