### ISSUE TITLE
No Option To Disable Kits?

### ISSUE THREAD

**Issue by Pandaken** [ImagicalGamer/SurvivalGamesV3#130]
Sorry for my issues. But this config doesn't have option to disable kits? Here is the config for SGV3-
---
chestitems:
- - 261
  - 0
  - 1
- - 262
  - 0
  - 2
- - 262
  - 0
  - 3
- - 267
  - 0
  - 1
- - 268
  - 0
  - 1
- - 272
  - 0
  - 1
- - 276
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
- - 283
  - 0
  - 1
lightning_effect: "ON"
...
^^^^^^^^^
Any solutions thanks.

**Comment by ImagicalGamer** [comment]
RandomKit: false <-- add that to the bottom of your config.

**Comment by Pandaken** [comment]
lightning_effect: "ON"
RandomKit: false
...
It doesn't seem to work like this, is there anything else i should do?

**Comment by Pandaken** [comment]
Im using this .phar: The STABLEST RELEASE! SurvivalGamesV3 - V3.0.7!

**Comment by Taki21** [comment]
can u download zip?

**Comment by Pandaken** [comment]
yes. but what do i do with the zip?

**Comment by Taki21** [comment]
-_-

**Comment by Taki21** [comment]
u extract it

**Comment by Taki21** [comment]
and put in your plugins folder

**Comment by Taki21** [comment]
then

**Comment by Taki21** [comment]
u

**Comment by Taki21** [comment]
have

**Comment by Taki21** [comment]
devtools?

**Comment by Taki21** [comment]
if u do,

**Comment by Taki21** [comment]
restart ur server

**Comment by Taki21** [comment]
and tada

**Comment by Pandaken** [comment]
what is devtools?

**Comment by Taki21** [comment]
dont forget to delete phar though

**Comment by Taki21** [comment]
0-0

**Comment by Taki21** [comment]
https://forums.imagicalmine.net/plugins/imagicaldevtools.79/

**Comment by Pandaken** [comment]
i can't download that plugin i don't have an account for magical mine still getting it manually confirmed .-.

**Comment by Taki21** [comment]
[DveTools.zip](https://github.com/ImagicalGamer/SurvivalGamesV3/files/240909/DveTools.zip)

**Comment by Pandaken** [comment]
so i use this plugin, extract the SGV3 zip, and then restart server?

**Comment by Pandaken** [comment]
by use i mean upload

**Comment by Taki21** [comment]
yup

**Comment by Taki21** [comment]
u put both in ur plugins folder

**Comment by Pandaken** [comment]
do i upload the SGV3 zip into plugins folder?

**Comment by Pandaken** [comment]
nvm

**Comment by Taki21** [comment]
does it work?

**Comment by Pandaken** [comment]
wait it won't let me upload the zip to plugins folder

**Comment by Taki21** [comment]
extract zip upload extracted folder to plugins folder

**Comment by Taki21** [comment]
If u are wondering...
[How To Extract A Zip....zip](https://github.com/ImagicalGamer/SurvivalGamesV3/files/240940/How.To.Extract.A.Zip.zip)

**Comment by remotevase** [comment]
@Pandaken that is the wrong release. Use the latest one that I posted

**Comment by Taki21** [comment]
i told him to download the zip..
