### ISSUE TITLE
players can get out of their plate/spawnpoint

### ISSUE THREAD

**Issue by TonyWAV** [ImagicalGamer/SurvivalGamesV3#133]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

Players can get out of their plate/spawnpoint if they move slowly out of it.

**Comment by remotevase** [comment]
shouldnt happen. I believe we have fixed this in the stable release.
