### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGamesV3#134]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

```
ParseError: "syntax error, unexpected '$config' (T_VARIABLE), expecting function (T_FUNCTION)" (EXCEPTION) in "myzip:///plugins/SurvivalGamesV3-master(1).zip#SurvivalGamesV3-master/src/SurvivalGamesV3/SurvivalGamesV3" at line 735

```

**Comment by Driesboy** [comment]
Fixed
