### ISSUE TITLE
another syntax error

### ISSUE THREAD

**Issue by TonyWAV** [ImagicalGamer/SurvivalGamesV3#136]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

ParseError: "syntax error, unexpected 'public' (T_PUBLIC), expecting end of file" (EXCEPTION) in "/phar_SurvivalGamesV3-master (2)_lFqivpW6eLc048M.phar/src/SurvivalGamesV3/SurvivalGamesV3" at line 737

**Comment by Driesboy** [comment]
Master?

**Comment by TonyWAV** [comment]
yes
