### ISSUE TITLE
Cant set deathmatch spawn

### ISSUE THREAD

**Issue by erkam2002** [ImagicalGamer/SurvivalGamesV3#14]

**Comment by ImagicalGamer** [comment]
Are you running PocketMine - ImagicalMine or Genisys? If your running Genisys there's not much I can do, I'm focusing on ImagicalMine support right now.

**Comment by TheGalaxyLord** [comment]
I just tried it on IM and I also can't set DM

**Comment by ImagicalGamer** [comment]
Download the latest .ZIP version from here and compile it, some of the PHP7 issues are gone, I was able to set a deathmatch spawn.

**Comment by TheGalaxyLord** [comment]
Nope still doesn't work
