### ISSUE TITLE
RAM use Lagg (reagain)

### ISSUE THREAD

**Issue by NikeboyHU** [ImagicalGamer/SurvivalGamesV3#140]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue is for SurvivalGamesV3, and not any other plugin.
- [ ] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
* = required

* Please state the server provider below (EG: PocketMine, ImagicalMine, Genysis etc):

* Please state the issue below:

Are there any errors in the console? If so, state them below:

Are there any crash dumps? If so, please paste it below (Paste the entire crash dump, not just the part that it tells you to):

RAM bug: RAM use a huge mistake , because the plugin continuously and endlessly running, eg . 'X' GB amount of RAM is not enough for the plugin

**Comment by Driesboy** [comment]
I dont have memory leak what server system do you use?

**Comment by NikeboyHU** [comment]
MultiCraft server manager, but 3 GB RAM not enough this plugin + 2 more server running on VPS, but this plugin all-memory used, and crashing server, and any server crash, AND when crash, blocking server-net (RakLibInterface)...

**Comment by remotevase** [comment]
Yes, this is an issue with all server systems. Not with the plugin
