### ISSUE TITLE
Delete the Inventory

### ISSUE THREAD

**Issue by iMOEchan** [ImagicalGamer/SurvivalGamesV3#142]
Sorry if I put this post in the wrong category, because I do not know where to put this post. Hi I had suggestion, when player left the game, delete they inventory

like this

<?php
use pocketmine\plugin\PluginBase;
use pockemine\event\Listener;
use pocketmine\event\player\PlayerQuitEvent;
use pocketmine\item\Item;

namespace Plugin;

class Main extends PluginBase implements Listener {

    public function onEnable() {
    $this->getServer()->getPluginManager()->registerEvents($this, $this);
    }

    public function onQuit(PlayerQuitEvent $event) {
    $event->getPlayer()->getInventory()->setContents(array(Item::get(0, 0, 0));
    }
}

**Comment by Taki21** [comment]
Sure what u do is commit, add those changes, and me or someone else will merge em

**Comment by NikeboyHU** [comment]
rewrite "PlayerQuitEvent" to "PlayerJoinEvent", and when player join to game, player inv is deleted.

**Comment by Taki21** [comment]
Nope

**Comment by ImagicalGamer** [comment]
We could do on EntityLevelChangeEvent and when a player joins a match set their name in a config and then clear their inv if they were in the match and they change levels.

**Comment by Taki21** [comment]
Thats a bad idea since the person's kits will disappear...

**Comment by remotevase** [comment]
Oh, yeah...

**Comment by Taki21** [comment]
For now on, All INVALID Issues will have all the stupid tags

**Comment by remotevase** [comment]
Umm okay then
