### ISSUE TITLE
Game start don't working!

### ISSUE THREAD

**Issue by NikeboyHU** [ImagicalGamer/SurvivalGamesV3#144]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue is for SurvivalGamesV3, and not any other plugin.
- [ ] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
* = required

* Please state the server provider below (EG: PocketMine, ImagicalMine, Genysis etc):

* Please state the issue below:

Are there any errors in the console? If so, state them below:

Are there any crash dumps? If so, please paste it below (Paste the entire crash dump, not just the part that it tells you to):

CRITICAL Plugin error in main (Multicraft server manager):
08.05 18:18:16 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///plugins/SurvivalGamesV3_v3.0.3.phar/src/SurvivalGamesV3/SurvivalGamesV3.php on line 355

config.yml and new coords don't refix this.
Arena join working, but game start doesn't working, and flood in Console this message.
Please try fix this.

**Comment by Driesboy** [comment]
first : this project is dead

**Comment by ImagicalGamer** [comment]
Delete the config folder it looks like you updated the plugin without deleting the odd config.

**Comment by remotevase** [comment]
@ImagicalGamer yes, many people are getting this issue. It's completely invalid for us

**Comment by NikeboyHU** [comment]
Well, delete source config... But... Nothing, don't repair this problem... :/

**Comment by remotevase** [comment]
No!!! Delete the whole config, ranks, and all of that!
