### ISSUE TITLE
Player lock movement bug

### ISSUE THREAD

**Issue by TonyWAV** [ImagicalGamer/SurvivalGamesV3#145]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

Players can really get out of their plate/spawn point if they slowly move out.
Please check it @Driesboy

**Comment by Driesboy** [comment]
I will check this soon

**Comment by Driesboy** [comment]
I am on school now

**Comment by ImagicalGamer** [comment]
Known Genisys issue please use the Genisys branch (if we still have one).

**Comment by Driesboy** [comment]
i think if we use the old one without head moving it will work
