### ISSUE TITLE
Plugin startup crash!

### ISSUE THREAD

**Issue by NikeboyHU** [ImagicalGamer/SurvivalGamesV3#148]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue is for SurvivalGamesV3, and not any other plugin.
- [ ] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
* = required

* Please state the server provider below (EG: PocketMine, ImagicalMine, Genysis etc):

* Please state the issue below:

Are there any errors in the console? If so, state them below:

Are there any crash dumps? If so, please paste it below (Paste the entire crash dump, not just the part that it tells you to):

New update bug... Crashing plugin, here it a log:
Loading plugin 'ClearLagg' with incompatible API version (the plugin API is not compatible with ImagicalMine API version 2.0.0)
16.05 15:03:11 [Server] WARNING Loading plugin 'SurvivalGamesV3' with incompatible API version (the plugin API is not compatible with ImagicalMine API version 2.0.0)
16.05 15:03:11 [Multicraft] Server shut down (starting)
16.05 15:03:11 [Multicraft] Restarting crashed server in 5 seconds
16.05 15:03:11 [Multicraft] Stopping server!

Please fix it.

**Comment by remotevase** [comment]
IMAGICALMINE DOES NOT WORK WITH MULTICRAFT
THIS IS AN INVALID ISSUE FOR ANYTHING
SIMPLE FIX: STOP USING MULTICRAFT

**Comment by NikeboyHU** [comment]
Multicraft the best server manager, i created crash dump for you.
Crash dump:
ImagicalMine Crash Dump Mon May 16 16:45:11 CEST 2016

Error: syntax error, unexpected 'else' (T_ELSE)
File: /SurvivalGames_v3.0.3.phar/src/SurvivalGamesV3/SurvivalGamesV3
Line: 463
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[454] 			$player->sendMessage($this->prefix . "Spawn " . $this->mode . " has been registered!");
[455] 			$this->mode++;
[456] 			if($this->mode==25)
[457] 			{
[458] 				$player->sendMessage($this->prefix . "Now tap on a deathmatch spawn.");
[459] 				$config->set($this->currentLevel . "Deathmatch" , array($block->getX(),$block->getY()+1,$block->getZ()));
[460] 			}
[461] 			$config->save();
[462] 		}
[463] 		else if($this->mode==25)
[464] 		{
[465] 			$config = new Config($this->getDataFolder() . "/config.yml", Config::YAML);
[466] 			$level = $this->getServer()->getLevelByName($this->currentLevel);
[467] 			$level->setSpawn = (new Vector3($block->getX(),$block->getY()+1,$block->getZ()));
[468] 			$config->set("arenas",$this->arenas);
[469] 			$player->sendMessage($this->prefix . "You've been teleported back. Tap a sign to register it for the arena!");
[470] 			$spawn = $this->getServer()->getDefaultLevel()->getSafeSpawn();
[471] 			$this->getServer()->getDefaultLevel()->loadChunk($spawn->getFloorX(), $spawn->getFloorZ());
[472] 			$player->teleport($spawn,0,0);
[473] 			$config->save();

Backtrace:
#0 (): spl_autoload_call(string SurvivalGamesV3\SurvivalGamesV3)
#1 /src/pocketmine/plugin/PharPluginLoader(80): class_exists(string SurvivalGamesV3\SurvivalGamesV3, boolean 1)
#2 /src/pocketmine/plugin/PluginManager(183): pocketmine\plugin\PharPluginLoader->loadPlugin(string phar:///home/minecraft/multicraft/servers/server3/plugins/SurvivalGames_v3.0.3.phar)
#3 /src/pocketmine/plugin/PluginManager(327): pocketmine\plugin\PluginManager->loadPlugin(string /home/minecraft/multicraft/servers/server3/plugins/SurvivalGames_v3.0.3.phar, array Array())
#4 /src/pocketmine/Server(1883): pocketmine\plugin\PluginManager->loadPlugins(string /home/minecraft/multicraft/servers/server3/plugins/)
#5 /src/pocketmine/PocketMine(519): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/servers/server3/ImagicalMine_1.4.phar/, string /home/minecraft/multicraft/servers/server3/, string /home/minecraft/multicraft/servers/server3/plugins/)
#6 (1): require_once(string phar:///home/minecraft/multicraft/servers/server3/ImagicalMine_1.4.phar/src/pocketmine/PocketMine.php)

ImagicalMine version: 1.4 #0 [Protocol 60; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux //vps-domain// 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64
PHP Version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
CraftingTableFix 2.0-Alpha by hm for API(s) 1.13.0, 2.0.0
DevBAN 1 by Ragnok123 for API(s) 1.13.1
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
ZipPluginLoader 1.1.3 by aliuly for API(s) 1.10.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0

Any questions?

**Comment by remotevase** [comment]
> Multicraft the best server manager,

Yes, I understand that. The only problem is that it is not compatible with ImagicalMine. It doesnt matter if the plugin is causing a crash.
**The plugin works fine with ImagicalMine. The plugin causes crashes on Multicraft**
