### ISSUE TITLE
DM pos bug

### ISSUE THREAD

**Issue by NikeboyHU** [ImagicalGamer/SurvivalGamesV3#149]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue is for SurvivalGamesV3, and not any other plugin.
- [ ] This is not a suggestion, but an actual issue 
NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
* = required

* Please state the server provider below (EG: PocketMine, ImagicalMine, Genysis etc):

* Please state the issue below:

Are there any errors in the console? If so, state them below:

Are there any crash dumps? If so, please paste it below (Paste the entire crash dump, not just the part that it tells you to):

DM tap point position don't working, please fix it.

**Comment by remotevase** [comment]
Please use the fields provided and resubmit the issue
