### ISSUE TITLE
Death Match

### ISSUE THREAD

**Issue by Mike4l6** [ImagicalGamer/SurvivalGamesV3#153]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)--> ImagicalMine

! <--STATE ISSUE HERE-- > I am unable to set deathmatch spawn for the survival games so I can't set it up : / 

<--PUT ANY CONSOLE ERRORS HERE-->

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by remotevase** [comment]
A new release will be posted in a few minutes that fixes this.

**Comment by remotevase** [comment]
Fixed here
https://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/3.x

**Comment by Mike4l6** [comment]
Thank you :D

**Comment by remotevase** [comment]
Np. that was actually fixed yesterday or a day before, but I forgot to release it
