### ISSUE TITLE
Syntax error on "Line 887"

### ISSUE THREAD

**Issue by TonyWAV** [ImagicalGamer/SurvivalGamesV3#154]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->
Genisys
! <--STATE ISSUE HERE-->
Syntax Error
<--PUT ANY CONSOLE ERRORS HERE-->
[21:34:19] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected '}', expecting end of file" (EXCEPTION) in "/plugins/SurvivalGamesV3-master/src/SurvivalGamesV3/SurvivalGamesV3" at line 887
[21:34:19] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[21:34:19] [Server thread/EMERGENCY]: Please upload the "C:\Users\TONY\Downloads\Genisys\crashdumps/CrashDump_Thu_May_26-21.34.19-AWST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->
Genisys Crash Dump Thu May 26 21:34:19 AWST 2016

Error: syntax error, unexpected '}', expecting end of file
File: /plugins/SurvivalGamesV3-master/src/SurvivalGamesV3/SurvivalGamesV3
Line: 887
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[878]        				$server = Server::getInstance();
[879]        				$pos = new Vector3($randx, $randy, $randz);
[880]        				$tile = $level->getTile($pos);
[881]         			$chest = Block::get(Block::CHEST);
[882]         			$level->setBlock($pos, $chest);
[883]     				}
[884] 			}
[885] 		}
[886] 	}
[887] }
[888] 
[889] 
[890] 
[891] 
[892] 
[893] 
[894] 
[895] 
[896] 
[897] 

Backtrace:
#0 (): spl_autoload_call(string SurvivalGamesV3\SurvivalGamesV3)
#1 /src/pocketmine/plugin/FolderPluginLoader(48): class_exists(string SurvivalGamesV3\SurvivalGamesV3, boolean 1)
#2 /src/pocketmine/plugin/PluginManager(155): pocketmine\plugin\FolderPluginLoader->loadPlugin(string C:\Users\TONY\Downloads\Genisys\plugins\SurvivalGamesV3-master)
#3 /src/pocketmine/plugin/PluginManager(333): pocketmine\plugin\PluginManager->loadPlugin(string C:\Users\TONY\Downloads\Genisys\plugins\SurvivalGamesV3-master, array 

Array())
#4 /src/pocketmine/Server(1977): pocketmine\plugin\PluginManager->loadPlugins(string C:\Users\TONY\Downloads\Genisys\plugins\)
#5 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\TONY

\Downloads\Genisys\, string C:\Users\TONY\Downloads\Genisys\, string C:\Users\TONY\Downloads\Genisys\plugins\, string unknown)

Genisys version: 1.1dev #0 [Protocol 70; API 2.0.0]
uname -a: Windows NT TONZ 6.3 build 9600 (Windows 8.1 Home Premium Edition) AMD64
PHP version: 7.0.4
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
加载的插件:

**Comment by remotevase** [comment]
Going to take a look now

**Comment by remotevase** [comment]
# PROBLEM WITH THIS ISSUE
1. Using Genysis with the master branch

**Comment by Driesboy** [comment]
Fixed look genisys branch
