### ISSUE TITLE
Running while no one is on

### ISSUE THREAD

**Issue by Mike4l6** [ImagicalGamer/SurvivalGamesV3#157]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [Y] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [Y] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [Y] This issue is written in your native language for maximal clarity
- [Y] This issue does not have abbreveations. Abbreviations make it not understandable.
- [Y] This issue is for SurvivalGamesV3, and not any other plugin.
- [Y] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->

! <--STATE ISSUE HERE-->When someone logs out and theres only one player. The sign says its running and no one can join :/

<--PUT ANY CONSOLE ERRORS HERE-->

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by Mike4l6** [comment]
Also I'm not on Genisys

**Comment by remotevase** [comment]
This release fixed ithttps://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/3.1.2-NOT-TESTED

**Comment by Driesboy** [comment]
can you upload it to the genisys branch?

**Comment by remotevase** [comment]
I have told you this many times before. I hate Genysis. I don't use Genysis. I don't help Genysis branch. I AM NOT GOING TO BE/POSSIBLY TAKE THE CHANCE OF BEING AFFILIATED WITH GENYSIS!!!!!!!!!!!!!!!!!!!

**Comment by ImagicalGamer** [comment]
Genisys is amazing.

**Comment by Mike4l6** [comment]
3.12 crashes

**Comment by remotevase** [comment]
Really, @Mike4l6 oh, right. Gotta post latest release. For nowDownload latest src and compile, should work fine

**Comment by Mike4l6** [comment]
ok

**Comment by remotevase** [comment]
Oops, just reread that post and it sounded rude. Sorry about that, I hope you were able to understand what I was saying and in a not-rude way. Im sorry

**Comment by Mike4l6** [comment]
its ok :D

**Comment by Aericio** [comment]
Genisys = Lagisys :/

**Comment by remotevase** [comment]
Lol

**Comment by Taki21** [comment]
I like Genisys now. Since IM is inactive...

**Comment by Taki21** [comment]
they just gave up for no reason and i dont like people giving up...i made a switch

**Comment by ImagicalGamer** [comment]
I've always liked and used Genisys, there was something about the IM community that I loved, that's why I stuck with it

**Comment by remotevase** [comment]
I like ClearSky and ImagicalMine. I did not give up onIM, I still wanna continue the project

**Comment by Mike4l6** [comment]
Is ever gonna be a 3.12 that doesn't crash?

**Comment by remotevase** [comment]
Let's hope so. Just look at the new branch: https://github.com/Inactive-to-Reactive/SurvivalGamesV4

**Comment by ImagicalGamer** [comment]
um @remotevase your moving it to a new repo?

**Comment by remotevase** [comment]
It's already moved

**Comment by remotevase** [comment]
And you are a member of the organization that it is in

**Comment by ImagicalGamer** [comment]
xD I didn't know dat
