### ISSUE TITLE
[PROBLEM: WHAT TO DO?] someone stole this plugin

### ISSUE THREAD

**Issue by remotevase** [ImagicalGamer/SurvivalGamesV3#158]
https://github.com/CristaudoORG/Gladiators/blob/master/src/BudinoCraft/Main.php

**Comment by Driesboy** [comment]
its a fork if you dont want forks dont upload it to github

**Comment by TonyWAV** [comment]
Because he didnt fork it here and upload new one

**Comment by Driesboy** [comment]
credits?

**Comment by TonyWAV** [comment]
he have

**Comment by remotevase** [comment]
Not full credits, claims it is good own plugin, but says in main php that it is this plugin

**Comment by ImagicalGamer** [comment]
I will have it taken down by github

**Comment by ImagicalGamer** [comment]
who deleted the license file?

**Comment by remotevase** [comment]
Not me

**Comment by ImagicalGamer** [comment]
https://help.github.com/articles/dmca-takedown-policy/

**Comment by ImagicalGamer** [comment]
Once we fill that out and I send it from my email it will be removed. I just talked to GitHub support

**Comment by Dev-Kevo** [comment]
wow

**Comment by remotevase** [comment]
okay
