### ISSUE TITLE
[SUGGESTION] Cannot replace join sign

### ISSUE THREAD

**Issue by biswarm22** [ImagicalGamer/SurvivalGamesV3#160]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [ ] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it  ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->
Genisys
! <--STATE ISSUE HERE-->
Suggestion: Make it eaisier to replace deleted join signs. Example: Type on sign First line: sg Second line: sg name
<--PUT ANY CONSOLE ERRORS HERE-->

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by NikeboyHU** [comment]
Sign Tap working on plugin. 1 sign block place to random palace, and type to chat '/sg create <world name>' command, tap 24 join spawn point, new dm point, and automatically teleport back to spawn, and tap the sign, and join sign will be created if you working good that.

**Comment by remotevase** [comment]
Hmmm, well take it into consideration

**Comment by ImagicalGamer** [comment]
You can make your own signs.
Set the second line to the world name, set the last line to the prefix

**Comment by biswarm22** [comment]
@ImagicalGamer what is the prefix and is this the format
(firstline blank)
(world name)
(blank line)
(prefix)
