### ISSUE TITLE
(Genisys)

### ISSUE THREAD

**Issue by biswarm22** [ImagicalGamer/SurvivalGamesV3#161]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->

! <--STATE ISSUE HERE-->
can move off of pedstal, using genisys version
<--PUT ANY CONSOLE ERRORS HERE-->

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by Driesboy** [comment]
Why

**Comment by Driesboy** [comment]
Newest version?

**Comment by remotevase** [comment]
Please tick the checkboxes. Next time this happens, your issue will be disregarded

**Comment by biswarm22** [comment]
@remotevase sorry about that

**Comment by remotevase** [comment]
no problem. first time issue-ers mistakes are always disregarded except for a notice!

**Comment by ImagicalGamer** [comment]
Must cancel the move event in genisys issue closed
