### ISSUE TITLE
[problem] Please, fix those problem

### ISSUE THREAD

**Issue by bbka123** [ImagicalGamer/SurvivalGamesV3#165]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is written in your native language for maximal clarity
- [ ] This issue does not have abbreveations. Abbreviations make it not understandable.
- [ ] This issue is for SurvivalGamesV3, and not any other plugin.
- [ ] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->

! <--STATE ISSUE HERE-->

<--PUT ANY CONSOLE ERRORS HERE-->

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by bbka123** [comment]
1.the setrank is bad, please fix itx
2.when players in sg , if players leave server, Inventory isn't clearall, please fix it

**Comment by bbka123** [comment]
And can you add player ranking,i sure this sg will be perfect

**Comment by remotevase** [comment]
This issue is not understandable
