### ISSUE TITLE
[SUGGESTION] Making SG V4?

### ISSUE THREAD

**Issue by Taki21** [ImagicalGamer/SurvivalGamesV3#166]
So i was thinking, after completing bugs, we can add extra - ordinary (lol) features and customizable thingies (more of em) and make it 
# **SURVIVAL GAMES V4 DUN DUN DUN!**
What ya think?"

**Comment by remotevase** [comment]
Yeah, that's what I wanna do. Make a new organization for this plugin and have website and all that stuff

**Comment by Dev-Kevo** [comment]
O.0

**Comment by ImagicalGamer** [comment]
We need to do a FULL rewrite of the entire plugin and make it more efficient and use less memory

**Comment by Driesboy** [comment]
YES!!!

**Comment by remotevase** [comment]
Wait... You can assign multiple people now? AWESOME!

**Comment by TonyWAV** [comment]
can i join?

**Comment by Driesboy** [comment]
Where?
Op 4-jun.-2016 11:52 schreef "TonyWAV" <notifications@github.com>:

**Comment by WBTclancode** [comment]
Can I be in the team for testing

**Comment by remotevase** [comment]
Please do not use this repository until ImagicalGamer fully retakes control of it. For now, use the new repo found in the readme file

**Comment by ImagicalGamer** [comment]
I have already done a full rewrite I will post it after I get off work later.

**Comment by ImagicalGamer** [comment]
@WBTclancode Can you test the latest commit?
