### ISSUE TITLE
What is this (rank.yml)?? [QUESTION]

### ISSUE THREAD

**Issue by MateiGamingYTB** [ImagicalGamer/SurvivalGamesV3#17]

**Comment by ImagicalGamer** [comment]
It's for an uncoming feature. You can use /setrank [rank] [player] or vice versa. The ranks are: VIP, VIP+, YouTuber, YouTuber+. It gives them kits at the start of the game based on their rank.

**Comment by ImagicalGamer** [comment]
The feature works but isn't PHP7 enabled so if your using anything but PocketMine it won't work.

**Comment by remotevase** [comment]
I am working on fixing that

**Comment by ImagicalGamer** [comment]
It works but needs some changes. I'll fully finish ranks now.

**Comment by MateiGamingYTB** [comment]
setrank is added? or coming soon adding?

**Comment by ImagicalGamer** [comment]
It is added, if your running PocketMine it will work.
