### ISSUE TITLE
Says "ImagicalMine DOES NOT WORK WITH PHP7 YET"

### ISSUE THREAD

**Issue by remotevase** [ImagicalGamer/SurvivalGamesV3#18]
We updated it and now the majority of it works

**Comment by ImagicalGamer** [comment]
Yea the majority, but it doesn't fully function with ImagicalMine and PHP7. I found our main issue on line 294. "Call to undefined method pocketmine\level\Level::setSpawn()" (EXCEPTION) in "/SGV3.phar/src/SurvivalGamesV3/SurvivalGamesV3" at line 294" But idk what to do.

**Comment by remotevase** [comment]
hmm... I will check like 294, but I may not find anything wrong
