### ISSUE TITLE
Does the plugin work in Genisys?

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalGamer/SurvivalGamesV3#22]

**Comment by erkam2002** [comment]
Yes ik but in 3.0.1 work it bruh xD

**Comment by XiangZhao969** [comment]
Nice. (Any bug bruh?)

**Comment by ImagicalGamer** [comment]
Version 3.0.1 had numerous PHP7 updates and bug fixes. You can get it [HERE](http://forums.imagicalmine.net/plugins/survivalgames.68/) if you get any console errors or bugs on Genisys let me know and I will make a Genisys repo.

**Comment by ImagicalGamer** [comment]
Issue closed question answered.
