### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by astersx** [ImagicalGamer/SurvivalGamesV3#24]
I dont know how it work,  i set arena,  then i tp to spawn,  and after i die i tp to same world!!
I didnt do any setting, it loaded all auto

How to set join sign

**Comment by astersx** [comment]
Oh,  fix it xd

**Comment by ImagicalGamer** [comment]
Delete SurvivalGamesV3 file if you don't have a sign placed before you set the arena

**Comment by astersx** [comment]
Yes,  i learned all in hard way,  omg im so happy that a SG plugin is made :3!!!
