### ISSUE TITLE
Request Items keep

### ISSUE THREAD

**Issue by astersx** [ImagicalGamer/SurvivalGamesV3#25]
hi,  can i request to make a way so players wont lose items?

**Comment by remotevase** [comment]
You can request it, but it probably will not be implemented. There are many reasons for this. <br>
1) If you gain blocks during the game, you would be able to build all over the spawn world
2) According to MCPE physics, when a player dies, they lose all of their items

**Comment by astersx** [comment]
You cant break sg arena,  only items from chest, anyway i removed it alone :D

**Comment by remotevase** [comment]
lol, yeah

**Comment by astersx** [comment]
You should add a config,  with,  reset-items:true or false   .  Owners who have survival server and wanna to add a little action,  will can play game without being annoyed by inventory reset.

My server is survival and keepinventory is true (genysis)!  So on dead,  no drop items!!

**Comment by ImagicalGamer** [comment]
We will take that into consideration that is a good idea for the config.
