### ISSUE TITLE
On game start glich

### ISSUE THREAD

**Issue by astersx** [ImagicalGamer/SurvivalGamesV3#26]
It seems that players are not stuck!!  they get pulled back,  but is like you walk with lag,  you should borrow code from a plugin with command /freeze!!!

And players attack each other with bows on game start,  is funny,  but i banned bows!!

Anyway great plugin,  is amazing and easy to set!!!

**Comment by astersx** [comment]
And players after dead are not teleported to spawn,  for some reason!! I set a MagicTeleportal on spawnpoint so they tp on spawn this way :+1:

**Comment by remotevase** [comment]
Yes, we are working on implementing the "freeze until match starts" but it may only come out in version 4 or 5... :(

**Comment by astersx** [comment]
Is all ok!!  Your plugin is still amazing!! Take your time,  and keep it alive !!  :)

**Comment by ImagicalGamer** [comment]
The players teleport when they respawn, it sounds like your running Genisys. We added support but all these bugs happen on Genisys and I haven't been able to re-create them on ImagicalMine.

**Comment by ImagicalGamer** [comment]
Genisys is very buggy when running SGV3 and it's not recommended to use this plugin on it. I will fix the movement bug.

**Comment by astersx** [comment]
Nono!!  If a player die,  he is teleported to arena spawn point!!  He is not going on lobby world,  becouse there is not config ;)

**Comment by ImagicalGamer** [comment]
The config has nothing to do with that, it's a Genisys bug. If you are fine withe this I will make it kick the player when they die so they respawn in the lobby world with Genisys.

**Comment by ImagicalGamer** [comment]
I also apologize for the bugs you are experiencing we test this using ImagicalMine not Genisys so we don't find Genisys bugs.

**Comment by ImagicalGamer** [comment]
What were you talking about with the bows? It gives them bows when the game starts?

**Comment by astersx** [comment]
Nono!!!  Becouse i delleted inventory reset,  players use bows to kill others in freeze mode!!!
Cant you add godmode,  until game start?

**Comment by ImagicalGamer** [comment]
Ah. That's not really our issue but I might be able to add that. Were trying to focus on bigger problems right now An grace period is being implemented and that will solve your issue.

**Comment by astersx** [comment]
Is ok,  players love gliches,  they think they are special,  like some hacker xd!!  All players from my sv love your plugin!!! Some rage at first,  wen they inventory reset xd!  Some are afraid!!   But i fixed and some really like it!! 

Anyway inventory reset is not your fault,  i should have checked it first ;)!!! 


And current gliches can be fixed, 'by building  some large spaces betwen players,  and on player respawn just put a magic teleportal and they go back an hub instant ;)

**Comment by ImagicalGamer** [comment]
I have it set so when players respawn it takes them to the hub.

**Comment by ImagicalGamer** [comment]
But thanks for the support! Also whats your servers IP and port?

**Comment by ImagicalGamer** [comment]
@astersx Download the latest version [HERE](forums.imagicalmine.net/plugins/survivalgames.68/download?version=129) now you won't need the portal!

**Comment by astersx** [comment]
buildmcpe.eu:19132

**Comment by astersx** [comment]
Link say error 404

**Comment by astersx** [comment]
Hi!! Your plugin had no problems , it was mspawns at fault!!!  It keep others go to default spawn :0!!!

**Comment by ImagicalGamer** [comment]
I just joined, cool server. I do see the movement issue your having. I'm fixing it now.

**Comment by ImagicalGamer** [comment]
Fixed! Player's can't turn their heads but they also cant leave their "plate".

**Comment by astersx** [comment]
My sv is cool? Thx,  i alone work on it,  i only have a helper to kick trollers :)

About move glich,  take your time :),

**Comment by ImagicalGamer** [comment]
Move glitch is fixed. =D.

**Comment by astersx** [comment]
So fast =) , i will add now!!

**Comment by ImagicalGamer** [comment]
Wait I'm making a release the TestMain file could corrupt the plug if you download the zip.

**Comment by ImagicalGamer** [comment]
@astersx [HERE](https://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/V3.0.3).

**Comment by remotevase** [comment]
great!

**Comment by astersx** [comment]
Im just editing the src files i download last :3,  thx for link!!!
And movement fixed , i cant think of more issues for now :)
