### ISSUE TITLE
How many arenas can I have? [QUESTION]

### ISSUE THREAD

**Issue by astersx** [ImagicalGamer/SurvivalGamesV3#27]
I see arena is saved in config,  how many arenas can i make? I just prepared a new map 😅

**Comment by ImagicalGamer** [comment]
Unlim arenas.

**Comment by astersx** [comment]
Cool,  thx ;)

**Comment by astersx** [comment]
Dont work,  it overwrite my current arena,  and didnt let me to set up :(

**Comment by astersx** [comment]
Oh no,  sometimes it have a error,  were it skip arena set up!! I need kick all players and retry until it works!! Anyway i did it :)

**Comment by astersx** [comment]
Hi! How can OPs edit arena? I need set rank op? If so what command?

**Comment by ImagicalGamer** [comment]
Can't edit the arena after it has been made, disable SurvivalGamesV3 and arenas can be built on, then re-enable it. Or delete the SurvivalGamesV3 folder and build your arenas and set them again.

**Comment by astersx** [comment]
Okay,  i knew that,  but i tought there was some op options!!  All is ok now ;)
