### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by kaitododoyt** [ImagicalGamer/SurvivalGamesV3#28]
Notice: Undefined variable: player in phar://C:/Users/Kaito/Desktop/kaito php7/plugins/SurvivalGamesV3.phar/src/SurvivalGamesV3/SurvivalGamesV3.php on line 65
[21:35:14] [Server thread/CRITICAL]: "No se pudo pasar el evento 'pocketmine\event\player\PlayerRespawnEvent' a 'SurvivalGamesV3 v3.0.3': Call to a member function teleport() on unknown en SurvivalGamesV3\SurvivalGamesV3"
[21:35:14] [Server thread/CRITICAL]: Error: "Call to a member function teleport() on unknown" (EXCEPTION) in "/SurvivalGamesV3.phar/src/SurvivalGamesV3/SurvivalGamesV3" at line 65

**Comment by ImagicalGamer** [comment]
Genisys?

**Comment by ImagicalGamer** [comment]
Use the one found [HERE](http://forums.imagicalmine.net/plugins/survivalgames.68/reviews#review-129-16). If your not already.

**Comment by kaitododoyt** [comment]
[Server thread/CRITICAL]: ParseError: "syntax error, unexpected ';', expecting ',' or ')'" (EXCEPTION) in "/phar_SurvivalGamesV3-master_IDxLzckxlvktqLB.phar/src/SurvivalGamesV3/SurvivalGamesV3" at line 65

**Comment by ImagicalGamer** [comment]
Are you running Genisys?

**Comment by kaitododoyt** [comment]
no, pocketmine

**Comment by astersx** [comment]
Hi! It seems u made some sintax error,  u forgot to put  ) and ;   on line 65 and on other lines u put in place of ; u put -

**Comment by astersx** [comment]
a example $this->getServer()->getDefaultLevel()->loadChunk($spawn->getFloorX(), 

I dont think is right,  u missed )  and ; 

you sould wach all lines and search for sintax problems ;)

**Comment by astersx** [comment]
Is sintax error,  test the plugin pls to see . Is not server fault,  im still using the one from yesterday xd!!!

**Comment by ImagicalGamer** [comment]
Issue solved.
