### ISSUE TITLE
Add...

### ISSUE THREAD

**Issue by MateiGamingYTB** [ImagicalGamer/SurvivalGamesV3#29]
add in match chat no public chat, match chat for in match players no server players

**Comment by astersx** [comment]
Per world chat, use it!!

**Comment by ImagicalGamer** [comment]
So you want chat disabled?

**Comment by astersx** [comment]
He wanna that chat in survival to be local!!  But the plugin perworldchat fix that so all ok ;)

**Comment by ImagicalGamer** [comment]
Ah, I can implement that.

**Comment by ImagicalGamer** [comment]
Less plugs = Less lagg so every plug that isn't needed helps.

**Comment by astersx** [comment]
But for those who already use local chat, becouse i run many worlds hmm.....,  maybe they will interfere!!  :D
