### ISSUE TITLE
Tip/Popup (feature)

### ISSUE THREAD

**Issue by astersx** [ImagicalGamer/SurvivalGamesV3#31]
Hi! I use a plugin basicHud,  to show players money on screen (as u saw),  and hud and survivalgames use popup , so count and money,  interfere with each other,  can u show Tip instead of popup? add a config for that,  is not a must!!  So take your time!

**Comment by ImagicalGamer** [comment]
Yes I can change it to tip.

**Comment by ImagicalGamer** [comment]
Feature added.

**Comment by astersx** [comment]
So fast :3
