### ISSUE TITLE
GRACE PERIOD BEING ADDED!!!

### ISSUE THREAD

**Issue by remotevase** [ImagicalGamer/SurvivalGamesV3#33]
Many people are asking about this, so I created this issue for everyone to talk about it.
For your information, I am adding a grace period, but it is HIGHLY UNSTABLE, so it is not in the main php file. This may not come out for quite a while

**Comment by ImagicalGamer** [comment]
Better xD.

**Comment by remotevase** [comment]
@ImagicalGamer Fixed it!

**Comment by remotevase** [comment]
oops, I didnt add grace period. I just readded a feature that was already there! XD

**Comment by remotevase** [comment]
the "starting in 30 seconds" etc. thing

**Comment by remotevase** [comment]
I think I just added the correct code. Players do not take damage for 300 ticks, which is equivalent to 15 seconds! @ImagicalGamer Tell me if there are any bugs... Comment on the commit. Other than that, this is added!!!

**Comment by ImagicalGamer** [comment]
I'll test it now!

**Comment by ImagicalGamer** [comment]
Not working $starttime is still undefined.

**Comment by remotevase** [comment]
not in that branch, silly! In master branch! The code I committed doesnt crash the server, so its in Main Branch in the Main file!

**Comment by ImagicalGamer** [comment]
I downloaded master branch.

**Comment by remotevase** [comment]
are you sure? Try it again!

**Comment by ImagicalGamer** [comment]
I'm looking at syntax errors on pmt.mcpe.me.

**Comment by remotevase** [comment]
okay! Hope there arent too many!

**Comment by ImagicalGamer** [comment]
Just the undefined variable.

**Comment by remotevase** [comment]
In TestMain?

**Comment by remotevase** [comment]
Just fixed undefined variable

**Comment by ImagicalGamer** [comment]
Ok good testing now.

**Comment by remotevase** [comment]
yay!

**Comment by ImagicalGamer** [comment]
@remotevase can you join dev.narwhalcraft.net 26625 to test it with me? I need 2 players.

**Comment by ImagicalGamer** [comment]
lol def need to fix the move event to make sure they r on the ground.

**Comment by ImagicalGamer** [comment]
I know what dat is.... Fixing.

**Comment by remotevase** [comment]
I will join that server now. I will stay on until you we are done testing!

**Comment by ImagicalGamer** [comment]
Oke thx.

**Comment by remotevase** [comment]
simple fix, not too hard...

**Comment by remotevase** [comment]
so, we done testing? It works? @ImagicalGamer I will be available for testing in 5 hours...

**Comment by remotevase** [comment]
Why closed? It works?
