### ISSUE TITLE
Genisys Bug Report!

### ISSUE THREAD

**Issue by remotevase** [ImagicalGamer/SurvivalGamesV3#34]
For those of you wondering what's going on with genisys, A new branch was just created in order to fix "genisys only" issues

**Comment by astersx** [comment]
Cool!!!!

**Comment by remotevase** [comment]
Yup! Now we can fix the relogin issue! @ImagicalGamer sorry, but I only work on ImagicalMine but not Genisys

**Comment by ImagicalGamer** [comment]
=D It's fine. Re-Login issue being fixed now!

**Comment by astersx** [comment]
There is a issue were you spawn in same area as your enemy,  is so funny wen u see others in same spawn and kill each other =)),  i did nothing wrong on settings,  it happen for long time but i tought is my fault.

Now after i remake arenas,  i see this issue not my fault (maybe genisys)

**Comment by ImagicalGamer** [comment]
Genisys's fault. What other bugs/errors need to be fixed for Genisys?

**Comment by astersx** [comment]
Thats all for now!! i will test for other gliches  😊

**Comment by ImagicalGamer** [comment]
Players can't leave during a match and join in the arena! 
Update was tested on Genisys 1.1dev-154 [DOWNLOAD HERE](https://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/Genisys)

**Comment by astersx** [comment]
I got the source code,  i will try later :+1:
