### ISSUE TITLE
Chests

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGamesV3#36]
So only chests at spawn are refilled is this a bug or do I have to fly around the map and use a command on the chests

**Comment by EpicSteve33** [comment]
Otherwise this plugin runs really smooth I'm surprised this is the best sg plugin out there that ive ever used

**Comment by ImagicalGamer** [comment]
Yes, only the spawn chests refill. I can possibly make all chests refill and am working on random items to fill the chests. Thanks for the support!

**Comment by EpicSteve33** [comment]
Well if you get chests to work this will officially be the best sg plugin on pocketmine also I have one more request can u add waiting text because that would be cool to see while waiting for the game to start kinda like lbsg does

**Comment by EpicSteve33** [comment]
Oh and there is no winning message so players do not know if they won or not

**Comment by ImagicalGamer** [comment]
That's strange are you on Genisys or ImagicalMine?

**Comment by EpicSteve33** [comment]
I am on genisys

**Comment by erkam2002** [comment]
@ImagicalGamer  look at my pull request

**Comment by ImagicalGamer** [comment]
@erkam2002 thanks for the grammer fixes. @EpicSteve33 fixing Genisys issues now be sure to download from the Genisys branch.

**Comment by EpicSteve33** [comment]
Oh ok Thanks

**Comment by ImagicalGamer** [comment]
https://github.com/ImagicalGamer/SurvivalGamesV3/tree/Genisys Download and compile that at pmt.mcpe.me and it should be fixed.

**Comment by ImagicalGamer** [comment]
Issue should be fixed, taking chest refill into consideration
