### ISSUE TITLE
Players can't turn heads on plates

### ISSUE THREAD

**Issue by kaitododoyt** [ImagicalGamer/SurvivalGamesV3#39]
Man you changed something that makes players can not turn around on the spawn, and i have a question, why in the end isn't possible see the winner message?. 
Sorry for my english and thanks for you job in this.

**Comment by ImagicalGamer** [comment]
When on their plate it cancels all movement events it was to fix a Genisys issue where players can walk off plates. Were working on the win message issue, were not sure what causes it to not show. @remotevase any ideas? It's not showing the "You Won" message.

**Comment by remotevase** [comment]
Hmmm... I don't know...

**Comment by ImagicalGamer** [comment]
I think it's a Genisys bug. It's random on IM it will either send a chat message or a popup.

**Comment by astersx** [comment]
Anyway i plan to move on IM!!  Genisys cant hold 60+ players without lag!!  I even use SSD ;-;

**Comment by ImagicalGamer** [comment]
=/ IM was built for speed, I can easily hold 60+ players on 4GB of ram with IM, Genisys will hold 60+ but there will be huge lagg spikes.

**Comment by ImagicalGamer** [comment]
@astersx what host do you use for BuildMCPE or do you use a VPS?

**Comment by astersx** [comment]
i used a xen before,  now i use kvm,  yep vps!!

**Comment by astersx** [comment]
But i have survival maps,  and they are big!!  Maybe mining, breaking,  saving, will cause lots of lags?

**Comment by ImagicalGamer** [comment]
Nope, I would suggest not using TimeCommander to save maps. Allow it to auto save on server restarts to reduce lag spikes.

**Comment by astersx** [comment]
I only use timeCommander to clear entityes!!  I run 7 worlds,  maybe this is a problem 😅

**Comment by ImagicalGamer** [comment]
xD lol I am running 13 worlds on a DEV server using ImagicalMine with 8GB of RAM 2 cores and were running smoothly.

**Comment by erkam2002** [comment]
i have a 3gb ram and octa core cpu intel i7

**Comment by astersx** [comment]
sounds so good!!!  But genisys say is php7 fault!!  Sooo!! i will test imagical,  hope for better results 😄

**Comment by ImagicalGamer** [comment]
What's PHP7 fault? The bugs in plug? They only happen when running Genisys and PHP7 so it's a mix Genisys still has PHP5 support IM only supports PHP7.

**Comment by astersx** [comment]
Yep,  it seems,  whats wrong in Imagical,  are pulls back,  and kick for flying!!
But pulls back good for speed hackers,  and fly kick...  is bad,  only fly pull i wanna but no kick!!

**Comment by astersx** [comment]
This is offtopic,  can you fix keepinventory to work in imagicalmine? It always give error in console,  and is disturbing :(   !!

**Comment by ImagicalGamer** [comment]
In pocketmine.yml disable AntiFly and search for AntiFly by Lambo.

**Comment by ImagicalGamer** [comment]
@remotevase Grace period?

**Comment by astersx** [comment]
Lambo antifly still working?

**Comment by ImagicalGamer** [comment]
I'll fix it later.

**Comment by ImagicalGamer** [comment]
It's a simple change of a #.

**Comment by remotevase** [comment]
@ImagicalGamer got the code. Gonna add a commit, then create a branch just for now. Then, we will test it, and then delete that branch. After THAT, we will publish the new update! Will be done tomorrow!

**Comment by ImagicalGamer** [comment]
@remotevase you need to define $starttime

**Comment by remotevase** [comment]
oh, lol oops
