### ISSUE TITLE
2 players in same spawn

### ISSUE THREAD

**Issue by astersx** [ImagicalGamer/SurvivalGamesV3#42]
It happened  just now on IM

**Comment by ImagicalGamer** [comment]
That's strange @remotevase could it be caused by the grace period?

**Comment by ImagicalGamer** [comment]
Confirmed bug with IM users.

**Comment by ImagicalGamer** [comment]
@astersx download [THIS](https://www.mediafire.com/?uk6vc3ij2gss1zi) it is ImagicalMine stable.

**Comment by remotevase** [comment]
Shouldn't be affected by grace period. 24 people can join a match, but there aren't 24 spawn pedestals. Therefore, multiple people must be on one pedestal...
