### ISSUE TITLE
Did not tp to spawn when I won!

### ISSUE THREAD

**Issue by austina1212** [ImagicalGamer/SurvivalGamesV3#43]
It is really amazing what you have fixed to my PLUGIN :D but I did not tp to spawn when I won a game and the game doesn't end when there is no players in it I am running genisys also add my server to the test server board it is currently whitelisted but IP is Play.CubedPlay.net!

**Comment by remotevase** [comment]
1) Genesis, you said?
2) won't add your server to test because it's whitelisted. Unwhitelist it.

**Comment by austina1212** [comment]
Yea... You kinda have to add it to test list the first version of this plugin was made by me... :D please add it :D also tell ImagicalGamer that MyNameIsAnti did not steal it :) he helped me a lot :)

**Comment by ImagicalGamer** [comment]
Sup. I can add your server (creator credits). There is a bug where when the second to last person dies (then we have a winner) it doesn't teleport the winner until the loser who died respawns.

**Comment by remotevase** [comment]
oops lol! forgot that u were original creater of plugin. we will add ur server. thought you were some random person

**Comment by ImagicalGamer** [comment]
xD. Issues being fixed.
