### ISSUE TITLE
Game does not restart.

### ISSUE THREAD

**Issue by blui22** [ImagicalGamer/SurvivalGamesV3#44]
I am running the latest version of IM and the game will not end. It just keeps repeating Game ending in 1 seconds....

**Comment by remotevase** [comment]
Can anybody else confirm this?

**Comment by ImagicalGamer** [comment]
Not a confirmed bug re-make your arena.

**Comment by ImagicalGamer** [comment]
That was caused by our time mix up with the grace period, xD it added 300 ticks to the game when there was 1 second left making the game infinite, issue fixed now.

**Comment by remotevase** [comment]
XD that issue was hilarious
