### ISSUE TITLE
Chests (Genisys Only)

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGamesV3#49]
Players cannot open chest unless they are op, also love the improvements on the plugin recently 

**_PM Version:_** Genisys

**_Operating system:_** Linux Mint

**Comment by EpicSteve33** [comment]
Maybe if you add an option to have player break block or not it would help me because I have a plugin that protects everything

**Comment by EpicSteve33** [comment]
Like in config

**_Break Block:_** True/False

**Comment by remotevase** [comment]
Okay, not overly hard, but changes would apply to all worlds, not just the sg works

**Comment by ImagicalGamer** [comment]
The chests aren't our issue,  one of the other plugs you have is interfering with it. No where in our code does it use chests except for adding items to them which couldn't cause this issue.

**Comment by EpicSteve33** [comment]
That's strange because I removed this code and I was able to open chests with a non op account if I put it back then the chests act as if they are locked


```
public function onBlockBreak(BlockBreakEvent $event)
	{
		$player = $event->getPlayer();
		$level = $player->getLevel()->getFolderName();
		if(in_array($level,$this->arenas))
		{
			$event->setCancelled(true);
		}
	}
	
	public function onBlockPlace(BlockPlaceEvent $event)
	{
		$player = $event->getPlayer();
		$level = $player->getLevel()->getFolderName();
		if(in_array($level,$this->arenas))
		{
			$event->setCancelled(true);
		}
	}
```

**Comment by EpicSteve33** [comment]
I have no plugins that mess with chests maybe if you add something in the config to disable this it will make it more helpful because I don't like editing plugin code its just more convenient that way

**Comment by EpicSteve33** [comment]
Oops

**Comment by Taki21** [comment]
ill fix soon

**Comment by Taki21** [comment]
Works for me but, these functions: onBreak and OnPlace do not depend on opening the chests!
Probably its a bug with Genisys? Never used it btw

**Comment by Taki21** [comment]
fixed???
