### ISSUE TITLE
Join SG glitch [GENYSIS ONLY (So Far

### ISSUE THREAD

**Issue by blui22** [ImagicalGamer/SurvivalGamesV3#51]
So I have a player that joins then hits the join sign. When in the game quit to title then join again in a few miniutes. That player get the in game messages such as 8 minutes til death match. Also in death match when a player kills the last player and the last player taps Main Menu the winning player stays in the arena

**Comment by remotevase** [comment]
What Server Provider are you using? PocketMine, Genysis, ImagicalMine, ClearSky?
No one else has gotten this issue...

**Comment by Driesboy** [comment]
genisys i think so

**Comment by remotevase** [comment]
Double check, please. I work on PocketMine, ImagicalMine, and ClearSky. If it's Genisys, what version are you using? I think we fixed this a while ago...

**Comment by EpicSteve33** [comment]
I have the death issue in genisys also I download the latest genisys off git everyday

**Comment by blui22** [comment]
It's IM

**Comment by blui22** [comment]
I am using Imagical Mine

**Comment by remotevase** [comment]
Really? The plugin works fine on ImagicalMine, and this bug doesn't exist. I have tried it on 3 servers with no errors. Are you sure you are using the latest version?

**Comment by blui22** [comment]
Oh I have the Genesis version on ImagicalMine! Silly mistake!

**Comment by ImagicalGamer** [comment]
That's a Genisys issue, the player's data file shows that he/she is still in the arena.

**Comment by Taki21** [comment]
@ImagicalGamer 
I think we should remove support for Genesyis???

**Comment by Taki21** [comment]
We're getting invalid Issues and it's genesyis  fault if it malfunctions....not this plugin, this plugin is fully working

**Comment by remotevase** [comment]
No. The main branch already removed genysis support. The genysis branch removed pocketmine and imagicalmine support

**Comment by Taki21** [comment]
o_0 whaah Speak in Taki Language plz xD

**Comment by remotevase** [comment]
lol

**Comment by ImagicalGamer** [comment]
@Taki21 the main branch won't work with Genisys.

**Comment by remotevase** [comment]
So that's taki language!

**Comment by ImagicalGamer** [comment]
Yep xD.
