### ISSUE TITLE
The game runs with 0 people [GENYSIS ONLY]

### ISSUE THREAD

**Issue by Driesboy** [ImagicalGamer/SurvivalGamesV3#52]

**Comment by blui22** [comment]
I have the same issue but ipthe game is running with one player.i am using  ImagicalMine

**Comment by remotevase** [comment]
@blui22 you MUST be using some other server provider. All of the issues that you are reporting are not real issues in ImagicalMine.

**Comment by ImagicalGamer** [comment]
That isn't our issue the world is either corrupted or not loaded, delete the sign and the SurvivalGamesV3 folder and re-make the arena.

**Comment by Driesboy** [comment]
not working and it work with other minigames

**Comment by Taki21** [comment]
Lets Face it....Genisys and ImagicalMine are kinda different in some parts of code! So dont expect this to work 100% well with Genisys! It was mainly built for the simple ImagicalMine....

**Comment by remotevase** [comment]
Actually, @Taki21 we have a Genysis branch devoted to Genysis coding

**Comment by ImagicalGamer** [comment]
Issue closed, world isn't loaded or is corrupted.

**Comment by Taki21** [comment]
ik but i was thinking its mainly for ImagacilMine

**Comment by ImagicalGamer** [comment]
Genisys issue, this has been reported at least 5 times and I can't re-create it on IM onlt Genisys.
