### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGamesV3#53]
Idk what is going on it was working fine then this happend

`[Server thread/CRITICAL]: ParseError: "syntax error, unexpected 'else' (T_ELSE)"  at line 418`

**Comment by remotevase** [comment]
ImagicalMine? PocketMine? Genysis? ClearSky?

**Comment by EpicSteve33** [comment]
Genisys

**Comment by EpicSteve33** [comment]
Should I try ImagicalMine?

**Comment by EpicSteve33** [comment]
nvm I cant all my plugins have older APIs

**Comment by Taki21** [comment]
Oops....Ill see error

**Comment by EpicSteve33** [comment]
do u know how to fix it?????

**Comment by Taki21** [comment]
yes! About to fix

**Comment by Taki21** [comment]
This is now fixed :D

**Comment by EpicSteve33** [comment]
I guess I caused it XD

**Comment by Taki21** [comment]
lol

**Comment by EpicSteve33** [comment]
I will test it when I get home later tonight :)
