### ISSUE TITLE
/sg not working

### ISSUE THREAD

**Issue by blake0201** [ImagicalGamer/SurvivalGamesV3#54]
/sg not working it says invalid peramiters (i know my spelling is bad)

**Comment by ImagicalGamer** [comment]
Do /sg create [world]

**Comment by remotevase** [comment]
I'm pretty sure this was fixed in the latest update

**Comment by EpicSteve33** [comment]
same issue but its prolly genisys

**Comment by EpicSteve33** [comment]
@blake0201 what version of PM are you Using?

**Comment by ImagicalGamer** [comment]
xD it's not an issue I never added the help menu to the Genisys branch xD.

**Comment by EpicSteve33** [comment]
i'm using the main branch

**Comment by EpicSteve33** [comment]
oh it works but you need op to see anything I was using my non op account

**Comment by blake0201** [comment]
@EpicSteve33 latest
@ImagicalGamer Oh LOL XD
@EpicSteve33 Oh

**Comment by Taki21** [comment]
ok lol no more issues! : D
