### ISSUE TITLE
Should Have Message When Start

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGamesV3#57]
You guys should add this message to appear in chat when counter hits 0 
I would but  I broke it when I tried 

`$this->sendToAll("§7[§fS§4G§7] §7let the games begins");`

Message in Chat
**[SG] Let the Games Begin **

**Comment by remotevase** [comment]
1) That is incorrect coding of php
2) What version of PM are you using. Supposed to show up...

**Comment by EpicSteve33** [comment]
Genisys and I was Using code from my old plugin as an example

**Comment by remotevase** [comment]
Oh, that code may work in Genysis just not IM or PM or CS

**Comment by remotevase** [comment]
Lol, tapped wrong (mobile device)

**Comment by EpicSteve33** [comment]
Well I couldnt get it to work but I just want a popup in chat so players know the game has started

**Comment by EpicSteve33** [comment]
not a popup but a message in chat

**Comment by EpicSteve33** [comment]
If I added this to line 411 would it work


```
if($timeToStart<=0)
{
                              $player->sendMessage("§7[§fS§4G§7] §7let the games begins");
                              $this->refillChests($levelArena);
                              $this->refillChests($levelArena)
}
			      $config->set($arena . "StartTime", $timeToStart);
{
```

**Comment by EpicSteve33** [comment]
I'm still a beginner at php so I'm not exactly the best at it

**Comment by remotevase** [comment]
Basically. Thing is: we have a variable for [SG] to make it easier

**Comment by Taki21** [comment]
sendToAll can be coded as a function btw

**Comment by ImagicalGamer** [comment]
sendToAll would broadcast to all worlds?

**Comment by remotevase** [comment]
probably

**Comment by Taki21** [comment]
sendToAll() is not API function....Its gotta be coded manually

**Comment by Taki21** [comment]
like
use
`public function sendToAll(){
   foreach($world->getPlayers() as $players){
      $players->sendPopup("Hi!");
   }
   return;
}

**Comment by EpicSteve33** [comment]
But would that send a message in chat cuz it would look better in chat

**Comment by Taki21** [comment]
then do
sendMessage instead of sendPopup

**Comment by applqpak** [comment]
@Taki21 why all the extra, useless code?

public function sendToAll($message)
{

  $this->getServer()->broadcastMessage($message);

}

Add that, so now anywhere in you plugin you can just do $this->sendToAll("Hello!");

**Comment by Taki21** [comment]
no he means in the game that why i put dat code
its gonna be funny with people not playing SG

**Comment by EpicSteve33** [comment]
If I used this would it work?

```
public function sendToAll(){
foreach($world->getPlayers() as $players){
$players->sendPopup("Hi!");
}
return;
}
```

**Comment by EpicSteve33** [comment]
Like something like this?

```
public function sendToAll(){
foreach($world->getPlayers() as $players){
$players->sendMessage("§7[§fS§4G§7] §7let the games begins");
}
return;
}

if($timeToStart<=0)
{
                              $player->sendToAll("§7[§fS§4G§7] §7let the games begins");
                              $this->refillChests($levelArena);
                              $this->refillChests($levelArena)
}
                  $config->set($arena . "StartTime", $timeToStart);
{
```

**Comment by Taki21** [comment]
take out return srry

**Comment by applqpak** [comment]
@Taki21 Erhm.. What?

**Comment by Taki21** [comment]
since hes not using as a function xD

**Comment by Taki21** [comment]
wait....remove sendToAll

**Comment by Taki21** [comment]
sorry like this
foreach($world->getPlayers() as $players){
$players->sendMessage("§7[§fS§4G§7] §7let the games begins");
}

if($timeToStart<=0)
{
                              $player->sendToAll("§7[§fS§4G§7] §7let the games begins");
                              $this->refillChests($levelArena);
                              $this->refillChests($levelArena)
}
                  $config->set($arena . "StartTime", $timeToStart);
{

**Comment by ImagicalGamer** [comment]
foreach $playersarena as $p1
{
$p1->sendTip(TextFormat::GREEN . "Let the games begin!";
}
That will work because we used to have that exact same code in there but I removed it (caused chat lagg for some reason)

**Comment by Taki21** [comment]
sendTip???? Not a API function???

**Comment by ImagicalGamer** [comment]
Tip or Popup either worked for me.

**Comment by ImagicalGamer** [comment]
I used tip because someone had basic hud and it used popups.

**Comment by Taki21** [comment]
oh lol

**Comment by remotevase** [comment]
Still locked and limited, but reopened so we can add it...

**Comment by ImagicalGamer** [comment]
I'll add it.
