### ISSUE TITLE
Registering spawn points

### ISSUE THREAD

**Issue by stoastye85** [ImagicalGamer/SurvivalGamesV3#61]
When I do start the command everything is fine. As soon as I begin setting spawn points the numbers are out of sequence. Then it doesnt let me set spawn point for deathmatch. Please help I am more than happy to donate. I am running pocketmine genisys. Thank you.

Sheilaeisfun@gmail.com

**Comment by remotevase** [comment]
This may not be fixed for a while, because @ImagicalGamer is our genysis manager, but he's taking a short break.

**Comment by stoastye85** [comment]
Ok thanks foe the reply

**Comment by stoastye85** [comment]
Also I am trying to download plugins from..

https://forums.imagicalmine.net/plugins/survivalgames.68/

Although it is telling me download unavailable on the actual download
button. Please help. Thank you.

**Comment by applqpak** [comment]
Is he taking a break?

**Comment by ImagicalGamer** [comment]
@applqpak I'm taking a break from SGV3 to finish a few other things and do some stuff for 4LifeCraft were launching 3 new servers.

**Comment by applqpak** [comment]
Oke.

**Comment by ImagicalGamer** [comment]
If your holding an item in your hand it will cause this issue btw.

**Comment by stoastye85** [comment]
Tha k you

**Comment by remotevase** [comment]
Hmmm... Interesting... wonder why?

**Comment by stoastye85** [comment]
I set point empty handed and it works perfectly.  Thanks a million

**Comment by ImagicalGamer** [comment]
It's a PM issue, PocketMine registers that as a tap and the hand as a tap so it will double set spawns or go out of order.

**Comment by ImagicalGamer** [comment]
Issue solved
