### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VitorWilliam** [ImagicalGamer/SurvivalGamesV3#66]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [16:19:25] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [16:19:26] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [16:19:26] [Server thread/INFO]: Loading server properties...
[Server] [16:19:26] [Server thread/INFO]: Enable MainLogger to file
[Server] [16:19:26] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [16:19:26] [Server thread/INFO]: Starting Minecraft: PE server version v0.14.x beta/alpha
[Server] [16:19:26] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [16:19:26] [Server thread/INFO]: This server is running ClearSky version 1.1 "Sunrise" (API 1.13.1) Build 345
[Server] [16:19:26] [Server thread/INFO]: ClearSky is distributed under the LGPL License
[Server] [16:19:30] [Server thread/INFO]: Loading AlwaysSpawn v2.2.2
[Server] [16:19:30] [Server thread/INFO]: Loading DevTools v1.10.0
[Server] [16:19:30] [Server thread/INFO]: Loading WorldProtect v2.2.0
[Server] [16:19:35] [Server thread/INFO]: Enabling AlwaysSpawn v2.2.2
[Server] [16:19:35] [Server thread/INFO]: AlwaysSpawn Enabled!
[Server] [16:19:35] [Server thread/INFO]: Enabling DevTools v1.10.0
[Server] [16:19:35] [Server thread/INFO]: Loading source plugin SurvivalGamesV3 v3.0.3
[Server] 
[Server] Parse error: syntax error, unexpected 'public' (T_PUBLIC) in /storage/sdcard0/PocketMine/plugins/SurvivalGamesV3-master/src/SurvivalGamesV3/SurvivalGamesV3.php on line 90
[Server] [16:19:35] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] [16:19:35] [Server thread/EMERGENCY]: Please upload the "/storage/sdcard0/PocketMine/crashdumps/CrashDump_Wed_Mar_30-16.19.35-UTC_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[Server] [16:19:38] [Server thread/INFO]: Disabling AlwaysSpawn v2.2.2
[Server] [16:19:38] [Server thread/INFO]: AlwaysSpawn is no longer enabled! Did the server stop?
[Server] [16:19:38] [Server thread/INFO]: Disabling DevTools v1.10.0
[Server] 
[Server] Took too long to stop, server was killed forcefully!

**Comment by Driesboy** [comment]
see my version i will made pr
