### ISSUE TITLE
if you join match and than leave the server the game dont stop or will running with 0/24 players

### ISSUE THREAD

**Issue by Driesboy** [ImagicalGamer/SurvivalGamesV3#68]
if you join match and than leave the server the game dont stop or will running with 0/24 players

**Comment by ImagicalGamer** [comment]
Genisys?

**Comment by remotevase** [comment]
Probably

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
its the last bug for genisys i think you can make a leave world or leave match

**Comment by remotevase** [comment]
This is a playerdata bug with genysis that cannot be fixed.

**Comment by Driesboy** [comment]
You can use onleave()
And than teleport to worldspawn i use it with myplugin and it work!

**Comment by ImagicalGamer** [comment]
We tried that it didn't do anything, feel free to test that and if it works make a pull request.

**Comment by Driesboy** [comment]
ok i wil test it
