### ISSUE TITLE
Error: AddEntityPacket

### ISSUE THREAD

**Issue by NML32** [ImagicalGamer/SurvivalGamesV3#70]
I'm using Genisys PHP7 build #211

Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'SurvivalGamesV3 v3.0.3': Class SurvivalGamesV3\AddEntityPacket not found on SurvivalGamesV3\SurvivalGamesV3

**Comment by ImagicalGamer** [comment]
Does it crash your server?

**Comment by ImagicalGamer** [comment]
It's for lighting download from [THIS](https://github.com/ImagicalGamer/SurvivalGamesV3/tree/Genisys) repo, it is a Genisys stable version xD. I will update it.

**Comment by NML32** [comment]
Doesn't crash the server just throws errors in the console.

**Comment by remotevase** [comment]
'AddEntityPacket' isnt properly supported in Genysis. There is a difference between 'AddEntityPacket' in ImagicaMine-PocketMine vs. 'AddEntityPacket' in Genysis

**Comment by ImagicalGamer** [comment]
^^ So use the Genisys Branch for now.

**Comment by ImagicalGamer** [comment]
@EpicSteve33 @Driesboy whichever of you made a pull request for players turning their heads on the plates add it and make another pull request pls.

**Comment by EpicSteve33** [comment]
I thought it was way to buggy if you want me too I'll add it again

**Comment by EpicSteve33** [comment]
Cuz I added it while back

**Comment by ImagicalGamer** [comment]
Yea I will make another branch to test it.

**Comment by EpicSteve33** [comment]
https://github.com/ImagicalGamer/SurvivalGamesV3/pull/71

**Comment by ImagicalGamer** [comment]
thx, I had forgotten the code xD
