### ISSUE TITLE
Help needed to set SG up correctly

### ISSUE THREAD

**Issue by Dub-Boy** [ImagicalGamer/SurvivalGamesV3#72]
Has anyone got clear instructions to correctly set this plugin up?

**Comment by remotevase** [comment]
Yes. 1st) create your desired SG world. 
2) type /SG create <world name>
3) After you are tp-ed to the SG world, click on 24 of your desired spawn points
4) Click on a deathmatch spawn
5) You will be teleported back to the world that you were in before step 2. 
6) Click on a sign that will have all stats and allow users to join the match

**Comment by Dub-Boy** [comment]
Thanks :D

**Comment by NML32** [comment]
Could this be added to the readme?

**Comment by ImagicalGamer** [comment]
Yes.
