### ISSUE TITLE
Update the Genisys Branch

### ISSUE THREAD

**Issue by Dub-Boy** [ImagicalGamer/SurvivalGamesV3#73]
Please update the Genisys Branch thanks.

**Comment by ImagicalGamer** [comment]
I have some cool features planned for Genisys xD. We can't use the same code we use for IM, sadly. But I will update it today.

**Comment by Dub-Boy** [comment]
Great thanks can't wait for the update :)

**Comment by NML32** [comment]
Thanks for the quick responses and updates for Genisys.

**Comment by ImagicalGamer** [comment]
^^ No problem!

**Comment by ImagicalGamer** [comment]
Just published a small update, more will come today!

**Comment by erkam2002** [comment]
:D
