### ISSUE TITLE
PVP is off

### ISSUE THREAD

**Issue by Mike4l6** [ImagicalGamer/SurvivalGamesV3#74]
I can't pvp in the map I created :(

**Comment by ImagicalGamer** [comment]
Strange, this plugin doesn't affect PVP at all. If you have spawn protection and peaceful spawn it won't allow PVP in any worlds.

**Comment by ImagicalGamer** [comment]
Are you using ImagicalMine or Genisys?

**Comment by remotevase** [comment]
This is a feature configured in server.properties and pocketmine.yml no matter the version you are using. When you installed the server, you had the option to turn pvp on or off. This has nothing to do with the plugin

**Comment by Mike4l6** [comment]
ok its probably my spawn protection or other plugins sorry for this

**Comment by ImagicalGamer** [comment]
It's fine! xP
