### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ItzRadius** [ImagicalGamer/SurvivalGamesV3#75]
When the match starts you are still stuck and cant move and the text above the hot bar is still there.

**Comment by Taki21** [comment]
Do u get any errors in Console? If yes plz post it And we'll **try** to fix it!

**Comment by ImagicalGamer** [comment]
Genisys issue xP.

**Comment by ImagicalGamer** [comment]
Use the Genisys branch.

**Comment by blui22** [comment]
What is the link to the genisys branch

**Comment by ItzRadius** [comment]
I think it will be all good. Lel.

**Comment by remotevase** [comment]
https://github.com/ImagicalGamer/SurvivalGamesV3/tree/Genisys
