### ISSUE TITLE
Genisys player leaving peadstal

### ISSUE THREAD

**Issue by blui22** [ImagicalGamer/SurvivalGamesV3#76]
player can leave pedestal before start. this happened after i switched from imagicalmine to genisys.

**Comment by ImagicalGamer** [comment]
Can't use same repo, download from the Genisys branch for Genisys servers.

**Comment by Taki21** [comment]
@blui22 I HIGHLY Recommend you go back to ImagicalMine...Im not forcing u im just suggesting as Genesys API is kinda messed up and consists of way 2 much errors in plugins... MY OPINION DO **NOT** Criticize me 
just say GoAwayTaki instead....xD

**Comment by blui22** [comment]
@Taki21 Genisys makes the lagg go away. That's the main reason I switched. I would go back to ImagicalMine if they fixed the lagg.

**Comment by Taki21** [comment]
GOAwayTaki! xD
