### ISSUE TITLE
Request: Update Genisys branch

### ISSUE THREAD

**Issue by NML32** [ImagicalGamer/SurvivalGamesV3#79]
Could someone update the Genisys branch?

Thanks

**Comment by remotevase** [comment]
soon. Our main focus is ImagicalMine/Pocketmine, though

**Comment by NML32** [comment]
Ok, thank you.

**Comment by ImagicalGamer** [comment]
I will soon update the Genisys branch once the ImagicalMine branch is stable.

**Comment by remotevase** [comment]
Read the bullets in #88 for more info on this
