### ISSUE TITLE
Timer stuck at 0 and Error in console

### ISSUE THREAD

**Issue by kabluinc** [ImagicalGamer/SurvivalGamesV3#82]
when the timer reaches 0 it keeps flashing 0 and this error comes every second in console 

[Server thread/CRITICAL]: Could not execute task SurvivalGamesV3\GameSender: Call to undefined method pocketmine\level\Level::createTile()
 [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\level\Level::createTile()" (EXCEPTION) in "/phar_SurvivalGamesV3-master_1tYPQCMo_VJ_lcb.phar/src/SurvivalGamesV3/SurvivalGamesV3" at line 622

**Comment by ImagicalGamer** [comment]
ImagicalMine or Genisys?

**Comment by ImagicalGamer** [comment]
If your using Genisys PHP5 this plugin will not work correctly. Also it will not work with the SkyWars plugin on IM forums.

**Comment by kabluinc** [comment]
Using genisys php7 also tried on pocket mine and imagicalmine but same problem on all three

**Comment by ImagicalGamer** [comment]
If your using the ImagicalMine SkyWars plugin that's causing your issue. It's based off of this and can't run with it.

**Comment by kabluinc** [comment]
I'm not using sky wars plugin and this is happening on all 3 versions of pocketmine

**Comment by ImagicalGamer** [comment]
Can I see a list of plugins your running.

**Comment by kabluinc** [comment]
FloatingTexter v1.0, Slapper v1.2.9.3, AdminFun v1.0.0, EconomyAPI v2.0.9, iProtector v3.1a, EconomyJob v2.0.4, EconomyLand v2.0.9, LeetTP v1.0.0, WorldEdit v1.0a, PurePerms v1.3.6, ReportRTS v1.1.3, SimpleAuth v1.7.1, SimpleAuthHelper v2.0.4, BanItem v2.1, AlwaysSpawn v2.2.2, CustomAlerts v1.6, 1vs1 v0.0.5, Nick v1.0.1, ChatCensor v1.4, FactionsPro v1.3.2, TapToDo v2.2.1, MagicTelePortal v1.3.2, Lightning_Strike v2, EconomyProperty v2.0.6, PureChat v1.3.3, Jail v2.1.2, SimpleWarp v2.1.0, WarpSigns v0.0.1

plus the survivalgames v3 plugin

**Comment by ImagicalGamer** [comment]
Strange. @remotevase I can't seem too find whats causing @kabluinc's issue. Any ideas?

**Comment by Dev-Kevo** [comment]
I think i fix that yesterday

**Comment by Dev-Kevo** [comment]
It was a typo

**Comment by Dev-Kevo** [comment]
Ops nvm

**Comment by remotevase** [comment]
Oh, he's using the unstable version. Dont use that yet.

**Comment by remotevase** [comment]
Use the official version that is published on ImagicalMine forums. The github version is unstable. He's using the github unstable version

**Comment by Driesboy** [comment]
i use the official from IM and i have the same bug

**Comment by Driesboy** [comment]
and i use php7 IM

**Comment by ImagicalGamer** [comment]
Strange, what plugins are you using?

**Comment by EpicSteve33** [comment]
According to the error this code wasn't defined 

`$chest = $level->createTile("chest", new Vector3($randX+4, $randY+1, $Z+4)); `

**Comment by EpicSteve33** [comment]
But that makes no sense because it looks like it is defined, maybe something is wrong somewhere else idk still a noob at php stuff

**Comment by remotevase** [comment]
You're right. This is not a real issue as the official from IM (I have tried it) does not have this issue. 
@Driesboy can we see a screenshot to prove that?

**Comment by EpicSteve33** [comment]
Maybe If we remove line 621 - 636 it will fix the error

**Comment by EpicSteve33** [comment]
I would test it but I'm in school and I have no access to my pc until I get home

**Comment by EpicSteve33** [comment]
I think removing this for now might help

```
else{
 				$chest = $level->createTile("chest", new Vector3($randX+4, $randY+1, $Z+4));
 				$chest->getInventory()->clearAll();
 				if($chest->getInventory() instanceof ChestInventory)
 				{
 					for($i=0;$i<=26;$i++)
 					{
 						$rand = rand(1,3);
						if($rand==1)
 						{
 							$k = array_rand($config->get("chestitems"));
 							$v = $config->get("chestitems")[$k];
 							$chest->getInventory()->setItem($i, Item::get($v[0],$v[1],$v[2]));
 						}
 					}									
 			}
```

**Comment by remotevase** [comment]
for now...

**Comment by EpicSteve33** [comment]
Should I do this?

**Comment by EpicSteve33** [comment]
https://github.com/ImagicalGamer/SurvivalGamesV3/pull/84
