### ISSUE TITLE
Grace Period

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGamesV3#85]
I found a SurvivalGames Plugin here https://github.com/PocketMineDevelopers/SurvivalGames Maybe we can barrow code from them to make a grace period

**Comment by EpicSteve33** [comment]
Just an idea

**Comment by Taki21** [comment]
I will work on grace period without that code dont worry xD I have a plan in mind btw im in computer class xD

**Comment by EpicSteve33** [comment]
Oh lol I was just trying to get grace done quickly lel

**Comment by Taki21** [comment]
xD
