### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by remotevase** [ImagicalGamer/SurvivalGamesV3#88]
- [x] Add random chest spawning
- [ ] Customization for chance that a chest will spawn
- [x] Add onleave event
- [x] Add grace period unstable (not tested)
- [x] Add grace period stable
- [x] Fix a few other issues
- [x] Add more config features
- [x] Add **option** to enable/disable lightning on death
- [x] Fix winner TP to spawn
- [x] Make the ImagicalMine Branch Stable
- [x] Update Genysis branch (after the above is completed)
- [x] Send messages only to people in SG world

**Comment by Taki21** [comment]
woah ! 88 Issues eh?

**Comment by remotevase** [comment]
lol

**Comment by remotevase** [comment]
2 Chest Spawn options:
Random spawning in world may be out of sg arena. To address that issue, maybe it should be spawn within radius of a spawnpoint. That radius would be configured in config. Maybe: User set 32 chest spawn points randomly, and each time, a total of 8 chests spawn using the above specific directions

**Comment by remotevase** [comment]
Grace period code `public function cancelDamage(EntityDamageEvent $event) { $entity = $event->getEntity(); if($entity instanceof Player){ if($entity->getLevel() == $this->level){ $event->setCancelled(); } } }`

Now with that code just need to add in the messages for 
$secondsofgraceleft

And the time for $timeofgrace
$timeofgrace also config

Lots of stuff for config

**Comment by Taki21** [comment]
Ctrl C + Ctrl V LOL

**Comment by Taki21** [comment]
Ya its really an enhancement

**Comment by remotevase** [comment]
I Wanna add label "Notice"

**Comment by Taki21** [comment]
Assignee?

**Comment by remotevase** [comment]
All of us

**Comment by Taki21** [comment]
How to add Label Notice?

**Comment by remotevase** [comment]
gg be back soon

**Comment by Taki21** [comment]
Oops xD

**Comment by ImagicalGamer** [comment]
I'm working with noDamageTicks for the grace period, we could get the time in the arena and if it is = or less that 780 damage is cancelled until X time.

**Comment by remotevase** [comment]
the noDamageTicks was recently corrupted in ImagicalMine and no longer works. It also fails in PocketMine 0.11 and up. We should use @Taki21's code (I provided it in a message above)

**Comment by ImagicalGamer** [comment]
I saw xD I just added that and it should be working.

**Comment by remotevase** [comment]
I would test, but pmt.mcpe.me is offline

**Comment by ImagicalGamer** [comment]
I'm using DevTools xD.

**Comment by ImagicalGamer** [comment]
If your available join NarwhalCraft.net 26625 to test

**Comment by ImagicalGamer** [comment]
I'm making a branch that will be an optimized version for home run servers, I'm gonna clean all the unnecessary code and features.

**Comment by remotevase** [comment]
cool, Sorry I was at school.  I can join soon, whenever your ready. Tell me when your ready to test.

**Comment by ImagicalGamer** [comment]
@Taki21 how do you get the custom labels or new ones?

**Comment by Taki21** [comment]
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/
i followed da instructions here

**Comment by ImagicalGamer** [comment]
Hehe

**Comment by Taki21** [comment]
lol xD

**Comment by Taki21** [comment]
3 More Checks To Go! I did some of them! I also created a STABLE WORKING Release! Check em out!

**Comment by Taki21** [comment]
https://github.com/ImagicalGamer/SurvivalGamesV3/releases

**Comment by remotevase** [comment]
cool! I'm gonna work on chest stuff next week. social studies tests this week (and they're quite hard, might I add)

**Comment by Taki21** [comment]
LOL XD Social Studies was always hard...
:D

**Comment by Taki21** [comment]
I have a break for a WEEK YAY

**Comment by remotevase** [comment]
nice, lucky you
week break = lots of coding and helping coding. 
Speaking of coding helping, I need help with EasyCMD. Making an issue there now

**Comment by ImagicalGamer** [comment]
Posted update! Thanks @Taki21 @remotevase for kinda taking over while I have been working on other projects. I'm gonna start taking requests and adding more to SGV3!

**Comment by Taki21** [comment]
np

**Comment by ImagicalGamer** [comment]
@remotevase @Taki21 I'm about to start on block hunt :smile: I will add you both as collaborators if you would like

**Comment by Taki21** [comment]
BLOCK HUNT OMG YES DEFINETLY IM HELPING LOL XD

**Comment by remotevase** [comment]
Well, I'm kinda clueless what these are
1) Blockhunt
2) Bedwars
3) Buildbattle

**Comment by remotevase** [comment]
Ooops lol. Of topic: Of you guys play on SQPE, you should join our forums! Http://sqpeforums.x10host.com/public_HTML (soon to be renamed)

**Comment by Driesboy** [comment]
i go now work on the genisys branch ok

**Comment by ImagicalGamer** [comment]
@Taki21 For sending messages in the GameSender task I would do:
`else if($time2>=500)
									{
									//yayaya whatevs here
									foreach($playersarena as $p)
									{
										$p->sendMessage("BRUH");
									}
									}`
Or would I need to use $time2 or did I format it all wrong? xD

**Comment by Taki21** [comment]
wait u mean $time2 as in the gametime?

**Comment by Taki21** [comment]
the format is correct but PLEASE im allergic to else if xD

**Comment by Taki21** [comment]
i prefer 

} else {
  if(){
  }
}

LOL

**Comment by Taki21** [comment]
(u can use else if but just be aware i sneeze at it so...)

**Comment by ImagicalGamer** [comment]
Guys I got a cool idea what if when the game is running it shows the time the match has left on the join sign in place of the world!!! Also we need to make it so $this->mode is only for OP any1 who taps a block while someone is making an arena sets spawn.

**Comment by Taki21** [comment]
Yes! Great Idea!

**Comment by ImagicalGamer** [comment]
Added it.

**Comment by remotevase** [comment]
@Taki21 why u allergic?

**Comment by Taki21** [comment]
LOL IDK

**Comment by ImagicalGamer** [comment]
@Taki21 @remotevase our plugin was stolen from a German developer before Austina worked on it, all the code that we didn't add is stolen what to do?

**Comment by Taki21** [comment]
report ... him
or
tell him peacefully not to do dat

**Comment by ImagicalGamer** [comment]
I'm saying I think Austina stole it.

**Comment by Taki21** [comment]
ohhhh

**Comment by Taki21** [comment]
Where is da other boi's repo?

**Comment by ImagicalGamer** [comment]
It's not public, I have the plugin.

**Comment by ImagicalGamer** [comment]
@Taki21 @remotevase my IP was banned from IM forums AGAIN... :cry:

**Comment by Taki21** [comment]
what da!? Dats weird...Maybe someone has same IP As u! Gotta check

**Comment by Taki21** [comment]
thelucyclub and Yato Dark 4U whos banned from forums have the same IP As u!

**Comment by ImagicalGamer** [comment]
that's weird what IP does it show they have?

**Comment by ImagicalGamer** [comment]
:cry: I'm devastated xP.

**Comment by Taki21** [comment]
i wont post it here

**Comment by Taki21** [comment]
post it in a conversation (this is public dats why xD)

**Comment by Taki21** [comment]
N***h *a*o*n*

**Comment by ImagicalGamer** [comment]
Can ya unban me

**Comment by Taki21** [comment]
(srry : ( me no has perm : ()

**Comment by ImagicalGamer** [comment]
:cry:

**Comment by ImagicalGamer** [comment]
OK

**Comment by ImagicalGamer** [comment]
:sob:

**Comment by Taki21** [comment]
:disappointed:

**Comment by ImagicalGamer** [comment]
:sob:

**Comment by ImagicalGamer** [comment]
@Taki21 @remotevase I wanna make a gun plug but how can I spawn a snowball or arrow? I looked on PM forums but everything there was outdated.

**Comment by Driesboy** [comment]
wait

**Comment by Driesboy** [comment]
https://github.com/Sandertv/PocketRPG

**Comment by Driesboy** [comment]
i hope it help

**Comment by ImagicalGamer** [comment]
thx

**Comment by Driesboy** [comment]
can i help you whit that plugin

**Comment by remotevase** [comment]
@ImagicalGamer im gonna unban you right this moment

**Comment by Taki21** [comment]
how do u unban @remotevase ??

**Comment by remotevase** [comment]
Confidential info on how, lets just say I'm part of @Keith 's and @ImagicalTom 's trusted staff team

**Comment by ImagicalGamer** [comment]
@remotevase can You ask @ImagicalTom to unban me pls.

**Comment by ImagicalGamer** [comment]
174.111.20.222 @remotevase

**Comment by remotevase** [comment]
Okay, lemme get on forums

**Comment by ImagicalGamer** [comment]
:+1:

**Comment by remotevase** [comment]
Someone banned that IP... Wonder why. Anyways, unbanned now

**Comment by ImagicalGamer** [comment]
Thanks @remotevase.

**Comment by remotevase** [comment]
np

**Comment by remotevase** [comment]
np

**Comment by ImagicalGamer** [comment]
Really plugin downloading disabled? Remember we don't want to kill the other communities.

**Comment by remotevase** [comment]
@ImagicalGamer I didnt disable it. Talk to @keithkfng
https://snag.gy/8WJjlD.jpg

**Comment by ImagicalGamer** [comment]
That would kill the IM community.

**Comment by ImagicalGamer** [comment]
Did you see the web API idea?

**Comment by remotevase** [comment]
Yes I did. IDK how to do it

**Comment by ImagicalGamer** [comment]
Look at the API of @DALTONTASTICS's twitter auth

**Comment by ImagicalGamer** [comment]
I just finished a working auth plugin =D. [HERE](https://github.com/ImagicalGamer/ImagicalAuth)

**Comment by remotevase** [comment]
@ImagicalGamer you should add a config

**Comment by ImagicalGamer** [comment]
I will add that!

**Comment by ImagicalGamer** [comment]
lmao I deleted a plugin and warned the guy because it was fake he must have other warns and now he is msging me whining about he can't download plugins because his account has been limited.

**Comment by remotevase** [comment]
@ImagicalGamer yeah I saw the plugin lol that dude is a Genysis user, btw

**Comment by ImagicalGamer** [comment]
Ik. Most of the users use Genisys as well as ImagicalMine. My servers run Im and Genisys, depends on what theme the server is.

**Comment by remotevase** [comment]
Interesting... I wouldnt do that because I prefer NOT to have issues with plugins. Therefore, my main server runs IM and I want the sub servers to run ClearSky for performance

**Comment by remotevase** [comment]
oops XD

**Comment by Taki21** [comment]
wait, can someone tell me how to make 2 servers on different ports? Im a noob...

**Comment by ImagicalGamer** [comment]
Change the port in server.properties

**Comment by ImagicalGamer** [comment]
For fac servers or PVP I use Genisys for the items and potions etc, for MiniGames and stuff I use IM for the performance.

**Comment by ImagicalGamer** [comment]
Any idea why this isn't making the directory?
`@mkdir($this->getDataFolder() . "/players/" . $name . ".yml");`
$name is properly defined btw

**Comment by remotevase** [comment]
Not /players/
Do players/

**Comment by ImagicalGamer** [comment]
I got it xD

**Comment by remotevase** [comment]
So, was the solution what I said? Wasn't exactly sure... Just and know of our will properly work

**Comment by ImagicalGamer** [comment]
I used the method used for creating a config.

**Comment by remotevase** [comment]
ah, k

**Comment by ImagicalGamer** [comment]
This project is pretty much dead.

**Comment by ImagicalGamer** [comment]
Just like ImagicalMine xD

**Comment by Mike4l6** [comment]
Make food / armor in chests

**Comment by remotevase** [comment]
no, not really @ImagicalGamer . I dont have much time nowadays, but I will in summer! I cant wait for summer to come around! I am also doing something that occupies my time, but that something will be done by satuday

**Comment by ImagicalGamer** [comment]
@remotevase It was a joke...

**Comment by remotevase** [comment]
Kk, lol, seemed true, though

**Comment by remotevase** [comment]
YAY! RANDOM CHEST SPAWNING MADE! UNTESTED, THOUGH. Someone please test ASAP.
Edited first post to suit this method and now we have 1 more thing to do!

**Comment by remotevase** [comment]
ON SERVER QUIT EVENT ADDED!!

**Comment by bbka123** [comment]
1./setrank is bad
Please fix, thank you
2.Please add When the player leaves the server, automatically empty the backpack.
3.Best to add a player points ranking
I believe this plugin will be perfect

**Comment by ImagicalGamer** [comment]
@remotevase @Driesboy @Taki21 Is this the correct way to make a custom function with multiple args?
` public function subtractMoney($player,$bal){
    $ammount = $this->getMoney($player);
    $money = new Config($this->getDataFolder() . "/players.yml", Config::YAML);
    $money->set($player,$ammount - $bal);
    $money->save();
  }`
So could I do $this->addMoney($player,$bal); ?

**Comment by Taki21** [comment]
$ammount = **$player**->getMoney();
It may work

**Comment by remotevase** [comment]
Guys, amount has one "m" not 2

**Comment by Taki21** [comment]
oh ya lol
