### ISSUE TITLE
Set Death Match Spawn Error

### ISSUE THREAD

**Issue by MichaelM04** [ImagicalGamer/SurvivalGamesV3#9]
So It was working fine for all 24 player spawn point sets then when it said set death match spawn it does nothing in game but in console it displays this error

Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'SurvivalGamesV2 v2.0.8': Call to undefined method pocketmine\level\Level::setSpawn() on SurvivalGamesV2\SurvivalGamesV2[14:20:27] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\level\Level::setSpawn()" (EXCEPTION) in "/plugins/SurvivalGamesV2-master/src/SurvivalGamesV2/SurvivalGamesV2" at line 294

**Comment by MichaelM04** [comment]
PocketMine-MP PHP7 Build

**Comment by ImagicalGamer** [comment]
It isn't fully updated to PHP7.

**Comment by ImagicalGamer** [comment]
Thanks for the PHP7 update! The plugin was made for a PHP5 client.
