### ISSUE TITLE
Console Error please fix!

### ISSUE THREAD

**Issue by bulutsun** [ImagicalGamer/SurvivalGamesV3#90]
#[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'SurvivalGamesV3': Class SurvivalGamesV3\AddEntityPacket not found on SurvivalGamesV3\SurvivalGamesV3
[18:09:11] [Server thread/CRITICAL]: ClassNotFoundException: "Class SurvivalGamesV3\AddEntityPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

Please fix issues thx!

**Comment by Driesboy** [comment]
V1!!!!!

**Comment by bulutsun** [comment]
Please fix error.

**Comment by remotevase** [comment]
You using genysis?

**Comment by remotevase** [comment]
sorry for the trouble, but could you please resubmit this issue using the new issue template?
