### ISSUE TITLE
Let the games begin!

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGamesV3#92]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.

Server Provider: ImagicalMine

Are there any errors in the console: nothing 

Are there any crash dumps: nope

The issue is when the game start it's supposed to say Let The Games Begin to everyone but it only displays the text to 1 player I believe it sometimes will not appear for everyone 

Code: `$pl->sendMessage($this->prefix . C::GREEN . "Let the games" . C::RED . C::BOLD . "begin!");`

**Comment by EpicSteve33** [comment]
It's really annoying because only a few people know when it has started I might provide gameplay later today if you need it idk why it happens maybe a ImagicalMine bug

**Comment by ImagicalGamer** [comment]
I think I know why.

**Comment by ImagicalGamer** [comment]
@remotevase idk why, probs an ImagicalMine bug.

**Comment by ImagicalGamer** [comment]
@EpicSteve33 delete your config and remake the arena, that may be causing an issue

**Comment by EpicSteve33** [comment]
Ok I will try this later today when I get home from school lel

**Comment by remotevase** [comment]
new pr that fixed it. I was gonna do it myself, but became lazy and just accepted the pr
