### ISSUE TITLE
Match Doesnt End When Killed Player Doesnt Respawn or Go to Main Menu

### ISSUE THREAD

**Issue by Heroata** [ImagicalGamer/SurvivalGamesV3#97]
As I said in title, when somebody killed, if he dont press to respawn or main menu button, game wont end and winner will stay at the arena. Trollers can use this issue

**Comment by Dev-Kevo** [comment]
This is true

**Comment by EpicSteve33** [comment]
@Dev-Kevo @Heroata what version of PocketMine are you on?

**Comment by EpicSteve33** [comment]
Because I think I know why but I don't think it can be fixed

**Comment by Heroata** [comment]
If devs change winning function, it can be fixed. Not hard. 

For example Get players on int, during the game, minus 1 when a player leave from game or world or when a player killed. Not hard.

 Using ImagicalMine 1.4

**Comment by EpicSteve33** [comment]
We would have to change a lot of stuff to make that work because the plugin checks for everything in that world and if players haven't respawned then they are technically still in that world it more pocketmine fault but maybe if the Devs look into it maybe they could add a function that checks when players die it seems like a lot of work to me(I'm lazy) lol

**Comment by Heroata** [comment]
Just use pocketmine\event\player\PlayerDeathEvent;

**Comment by remotevase** [comment]
I'll take a look

**Comment by remotevase** [comment]
I'm pretty sure that we fixed this...

**Comment by ImagicalGamer** [comment]
We never fixed it, but I know how.

**Comment by ImagicalGamer** [comment]
On PlayerDamageEvent when X amount of damage has been done before they die teleport them to spawn then let them die so the player dies in the default world instead of the arena.

**Comment by Heroata** [comment]
Lol better

**Comment by Heroata** [comment]
Fixed it with MSpawn Plugin's api. Should I pull?

**Comment by Heroata** [comment]
BTW Pulled
